-- 品类与六维扩展：知识层 product_type + 扩展品类 Shadow 结果。
-- 新品类是否进入正式业务候选集由 rsdp.ai.category.extended.enabled 控制，默认关闭。

CREATE TABLE IF NOT EXISTS knowledge_product_type (
    type_code VARCHAR(64) PRIMARY KEY,
    type_name VARCHAR(64) NOT NULL,
    business_category_code VARCHAR(16) NOT NULL,
    schema_category_code VARCHAR(16) NOT NULL,
    parent_type_code VARCHAR(64),
    aliases JSONB NOT NULL DEFAULT '[]'::jsonb,
    room_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    knowledge_version VARCHAR(16) NOT NULL DEFAULT '1.0',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_type_parent FOREIGN KEY (parent_type_code) REFERENCES knowledge_product_type(type_code)
);
CREATE INDEX IF NOT EXISTS idx_product_type_business_category
    ON knowledge_product_type(business_category_code, status, sort_order);
CREATE INDEX IF NOT EXISTS idx_product_type_schema_category
    ON knowledge_product_type(schema_category_code, status);

CREATE TABLE IF NOT EXISTS ai_category_shadow_result (
    shadow_id BIGSERIAL PRIMARY KEY,
    recognition_id VARCHAR(64) NOT NULL UNIQUE,
    rspu_id VARCHAR(64),
    image_id VARCHAR(64),
    legacy_category VARCHAR(16),
    extended_category VARCHAR(16),
    product_type VARCHAR(64),
    six_dim_result JSONB,
    confidence VARCHAR(16),
    difference_reason TEXT,
    model_version VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (recognition_id) REFERENCES ai_recognition(recognition_id) ON DELETE CASCADE,
    FOREIGN KEY (rspu_id) REFERENCES rspu_master(rspu_id),
    FOREIGN KEY (image_id) REFERENCES image_assets(image_id),
    CONSTRAINT fk_ai_category_shadow_product_type
        FOREIGN KEY (product_type) REFERENCES knowledge_product_type(type_code)
);
CREATE INDEX IF NOT EXISTS idx_ai_category_shadow_rspu ON ai_category_shadow_result(rspu_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_category_shadow_category ON ai_category_shadow_result(extended_category, created_at);

-- >>> PRODUCT_TAXONOMY_SEED (generated by scripts/generate_six_dim_dict_seed.js, do not edit manually) >>>
-- 扩展一级业务品类（Feature Flag 默认关闭，种子存在不代表进入正式业务候选集）
INSERT INTO category_dict (dict_type, dict_code, dict_name, sort_order, aliases, remark) VALUES
('category', 'DK', '书桌/写字台', 10, '["书桌","写字台","家庭办公桌","电脑桌"]', '家庭、酒店与书房使用的工作桌，不含 OF 办公职级语义'),
('category', 'MT', '床垫', 11, '["床垫","睡垫","弹簧床垫","乳胶床垫"]', '独立于床架的睡眠承托产品，内部结构仅在剖面或文字可见时判定'),
('category', 'MR', '镜子', 12, '["镜子","落地镜","穿衣镜","装饰镜"]', '以镜面、边框和安装支撑方式为主要结构的反射类家居产品'),
('category', 'RG', '地毯', 13, '["地毯","块毯","客厅毯","床边毯"]', '铺设于地面的织物或编织产品，以轮廓、图案、边缘和织造表面区分'),
('category', 'PD', '屏风/隔断', 14, '["屏风","隔断","折屏","空间分隔"]', '非柜类的空间分隔结构，包括折屏、滑动、悬挂与声学隔断'),
('category', 'CW', '窗帘/窗饰', 15, '["窗帘","窗饰","卷帘","百叶帘","罗马帘"]', '布艺开合帘、卷帘、百叶等窗口软装及其可见安装结构')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 二级产品类型知识层：独立旁路，不关联 rspu_master，不参与编码/报价/订单/同款
INSERT INTO knowledge_product_type
    (type_code, type_name, business_category_code, schema_category_code, aliases, room_tags, description, sort_order) VALUES
('DINING_CHAIR', '餐椅', 'FS', 'FS', '["餐桌椅","吃饭椅"]'::jsonb, '["DINING_ROOM"]'::jsonb, '用于餐桌周边的单人座椅', 1),
('LOUNGE_CHAIR', '休闲椅', 'FS', 'FS', '["休闲单椅","主人椅"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '以放松坐姿为主的单人椅', 2),
('ARMCHAIR', '扶手椅', 'FS', 'FS', '["有扶手椅","扶手单椅"]'::jsonb, '["LIVING_ROOM","STUDY"]'::jsonb, '两侧具有明确扶手的单人椅', 3),
('ACCENT_CHAIR', '装饰单椅', 'FS', 'FS', '["造型椅","点缀椅"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '以空间视觉点缀为主的单椅', 4),
('ROCKING_CHAIR', '摇椅', 'FS', 'FS', '["摇摇椅","弧底椅"]'::jsonb, '["LIVING_ROOM","BALCONY"]'::jsonb, '底部具有弧形摇杆或摇摆机构的座椅', 5),
('FOLDING_CHAIR', '折叠椅', 'FS', 'FS', '["可折椅","收折椅"]'::jsonb, '["DINING_ROOM","BALCONY"]'::jsonb, '框架可折叠收纳的座椅', 6),
('HANGING_CHAIR', '吊椅', 'FS', 'FS', '["秋千椅","悬挂椅"]'::jsonb, '["BALCONY","LIVING_ROOM"]'::jsonb, '座体通过吊链或吊绳悬挂的椅类', 7),
('BENCH', '长凳/床尾凳', 'FS', 'FS', '["长凳","床尾凳","换鞋凳"]'::jsonb, '["BEDROOM","ENTRYWAY","DINING_ROOM"]'::jsonb, '可容纳两人以上或用于床尾的长条座具', 8),
('OTTOMAN', '脚踏', 'FS', 'FS', '["脚凳","搁脚凳"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '与沙发或单椅配套的无靠背脚踏', 9),
('POUF', '坐墩', 'FS', 'FS', '["蒲团","软坐墩"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '低矮、多为软体的无靠背坐具', 10),
('STOOL', '矮凳', 'FS', 'FS', '["小凳子","无背凳"]'::jsonb, '["DINING_ROOM","ENTRYWAY"]'::jsonb, '低高度的无靠背单人凳', 11),
('CHAIR_LOUNGER', '单人躺椅', 'FS', 'FS', '["躺椅","贵妃椅"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '可支撑腿部伸展的单人躺坐具', 12),
('LOVESEAT', '双人沙发', 'SF', 'SF', '["二人位沙发","情侣沙发"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '主要容纳两人的小型沙发', 13),
('STRAIGHT_SOFA', '直排沙发', 'SF', 'SF', '["一字沙发","直线沙发"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '座位沿单一直线排列的沙发', 14),
('SECTIONAL_SOFA', '转角沙发', 'SF', 'SF', '["L型沙发","转角组合"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '座位在转角处连续延伸的沙发', 15),
('MODULAR_SOFA', '模块沙发', 'SF', 'SF', '["组合沙发","积木沙发"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '由多个可重组座位模块构成', 16),
('SOFA_BED', '沙发床', 'SF', 'SF', '["可睡沙发","折叠沙发床"]'::jsonb, '["LIVING_ROOM","GUEST_ROOM"]'::jsonb, '可展开或翻折为睡眠面的沙发', 17),
('RECLINER_SOFA', '功能沙发', 'SF', 'SF', '["电动沙发","伸展沙发"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '座位可躺倒或展开脚托的功能沙发', 18),
('CURVED_SOFA', '弧形沙发', 'SF', 'SF', '["弯沙发","月牙沙发"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '座位整体沿弧线排列的沙发', 19),
('CHAISE_SOFA', '贵妃/躺榻组合', 'SF', 'SF', '["贵妃沙发","躺位沙发"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '直排座位与长躺位组合的沙发', 20),
('COFFEE_TABLE', '茶几', 'TB', 'TB', '["客厅中心几","大茶几"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '用于沙发区中心的低桌', 21),
('SIDE_TABLE', '边几', 'TB', 'TB', '["沙发边几","小边桌"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '放置于沙发或座椅侧边的小几', 22),
('END_TABLE', '角几', 'TB', 'TB', '["角桌","端几"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '放置于沙发端部或墙角的小几', 23),
('C_TABLE', 'C形沙发边桌', 'TB', 'TB', '["C形边几","嵌入式边桌"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '底座可插入沙发或床下的C形小桌', 24),
('NESTING_TABLE', '子母/套几', 'TB', 'TB', '["套几","组合几"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '大小多张可嵌套收纳的小几组', 25),
('DRUM_TABLE', '鼓形几', 'TB', 'TB', '["鼓几","墩式边几"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '整体呈鼓或实心墩体的小几', 26),
('PEDESTAL_TABLE', '柱式小几', 'TB', 'TB', '["独柱几","圆盘底边几"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '由中央单柱支撑小台面的几类', 27),
('CONSOLE_TABLE', '玄关台/窄边桌', 'TB', 'TB', '["玄关桌","靠墙窄桌"]'::jsonb, '["ENTRYWAY","LIVING_ROOM"]'::jsonb, '靠墙摆放的窄长高台，过渡归入 TB', 28),
('TV_STAND', '电视柜', 'FC', 'FC', '["视听柜","地柜"]'::jsonb, '["LIVING_ROOM"]'::jsonb, '用于承放电视与视听设备的低柜', 29),
('SIDEBOARD', '餐边柜', 'FC', 'FC', '["餐厅边柜","餐具柜"]'::jsonb, '["DINING_ROOM"]'::jsonb, '放置于餐厅用于餐具与餐酒收纳的柜体', 30),
('CREDENZA', '边柜', 'FC', 'FC', '["矮边柜","靠墙柜"]'::jsonb, '["LIVING_ROOM","DINING_ROOM"]'::jsonb, '靠墙摆放的通用横向矮柜', 31),
('NIGHTSTAND', '床头柜', 'FC', 'FC', '["床边柜","床头小柜"]'::jsonb, '["BEDROOM"]'::jsonb, '放置于床侧的小型收纳柜', 32),
('DRESSER', '斗柜', 'FC', 'FC', '["抽屉柜","五斗柜"]'::jsonb, '["BEDROOM","LIVING_ROOM"]'::jsonb, '以多层水平抽屉为主的柜体', 33),
('WARDROBE', '衣柜', 'FC', 'FC', '["大衣橱","衣帽柜"]'::jsonb, '["BEDROOM","CLOAKROOM"]'::jsonb, '用于挂放与叠放衣物的高柜', 34),
('BOOKCASE', '书柜', 'FC', 'FC', '["书架柜","藏书柜"]'::jsonb, '["STUDY","LIVING_ROOM"]'::jsonb, '以层板收纳书籍的柜体', 35),
('DISPLAY_CABINET', '展示柜', 'FC', 'FC', '["陈列柜","玻璃展柜"]'::jsonb, '["LIVING_ROOM","DINING_ROOM"]'::jsonb, '具有透明门或开放展示面的柜体', 36),
('SHOE_CABINET', '鞋柜', 'FC', 'FC', '["玄关鞋柜","换鞋柜"]'::jsonb, '["ENTRYWAY"]'::jsonb, '用于收纳鞋履的玄关柜体', 37),
('WINE_CABINET', '酒柜', 'FC', 'FC', '["餐酒柜","葡萄酒柜"]'::jsonb, '["DINING_ROOM","LIVING_ROOM"]'::jsonb, '用于存放或展示酒瓶酒具的柜体', 38),
('ENTRY_CABINET', '玄关柜', 'FC', 'FC', '["入户柜","门厅柜"]'::jsonb, '["ENTRYWAY"]'::jsonb, '位于入户区的综合收纳柜', 39),
('MOBILE_CART', '移动柜/推车', 'FC', 'FC', '["带轮柜","收纳推车"]'::jsonb, '["DINING_ROOM","LIVING_ROOM"]'::jsonb, '底部带轮可移动的小柜或推车', 40),
('BAR_STOOL', '吧凳', 'BS', 'BS', '["高凳","无背吧凳"]'::jsonb, '["BAR","KITCHEN"]'::jsonb, '吧台高度的无靠背或低靠背凳', 41),
('BAR_CHAIR', '吧椅', 'BS', 'BS', '["高脚椅","有背吧椅"]'::jsonb, '["BAR","KITCHEN"]'::jsonb, '具有明确靠背的吧台高座椅', 42),
('COUNTER_STOOL', '中岛凳', 'BS', 'BS', '["厨岛凳","柜台凳"]'::jsonb, '["KITCHEN","DINING_ROOM"]'::jsonb, '匹配厨房中岛或柜台高度的高凳', 43),
('ADJUSTABLE_STOOL', '升降吧椅', 'BS', 'BS', '["气压吧椅","可调高吧凳"]'::jsonb, '["BAR","KITCHEN"]'::jsonb, '高度可通过气压或螺旋机构调节的吧椅', 44),
('BACKLESS_STOOL', '无靠背高凳', 'BS', 'BS', '["无背吧凳","高脚凳"]'::jsonb, '["BAR","KITCHEN"]'::jsonb, '无任何靠背构件的高凳', 45),
('TASK_CHAIR', '办公椅', 'OF', 'OF', '["职员椅","任务椅"]'::jsonb, '["OFFICE"]'::jsonb, '日常工位使用的人体工学办公椅', 46),
('EXECUTIVE_CHAIR', '班椅/高管椅', 'OF', 'OF', '["老板椅","总裁椅"]'::jsonb, '["OFFICE"]'::jsonb, '靠背较高、体量较大的高管办公椅', 47),
('GUEST_CHAIR', '访客椅', 'OF', 'OF', '["接待椅","会客椅"]'::jsonb, '["OFFICE"]'::jsonb, '用于办公接待或桌前访客的椅类', 48),
('STAFF_DESK', '职员桌', 'OF', 'OF', '["员工桌","办公桌"]'::jsonb, '["OFFICE"]'::jsonb, '单人或并列职员工位用办公桌', 49),
('EXECUTIVE_DESK', '班台', 'OF', 'OF', '["大班台","总裁桌"]'::jsonb, '["OFFICE"]'::jsonb, '体量大、台面宽厚的高管办公桌', 50),
('MANAGER_DESK', '主管桌', 'OF', 'OF', '["经理桌","主管台"]'::jsonb, '["OFFICE"]'::jsonb, '体量介于班台与职员桌之间的办公桌', 51),
('WORKSTATION', '屏风工位', 'OF', 'OF', '["卡位","格子间工位"]'::jsonb, '["OFFICE"]'::jsonb, '桌面与屏风组成的单人或多人工位系统', 52),
('CONFERENCE_TABLE', '会议桌', 'OF', 'OF', '["会议台","多人会议桌"]'::jsonb, '["OFFICE","MEETING_ROOM"]'::jsonb, '供多人围坐会议的大尺寸桌台', 53),
('TRAINING_TABLE', '培训桌', 'OF', 'OF', '["培训折叠桌","条桌"]'::jsonb, '["OFFICE","TRAINING_ROOM"]'::jsonb, '可并排、收折或翻板的培训用桌', 54),
('HEIGHT_ADJUSTABLE_DESK', '升降办公桌', 'OF', 'OF', '["站立办公桌","电动升降桌"]'::jsonb, '["OFFICE"]'::jsonb, '台面高度可调的办公桌', 55),
('FILING_CABINET', '文件柜', 'OF', 'OF', '["档案柜","资料柜"]'::jsonb, '["OFFICE"]'::jsonb, '用于文件档案分类收纳的办公柜', 56),
('OFFICE_BOOKCASE', '办公书柜', 'OF', 'OF', '["办公室书柜","文件书柜"]'::jsonb, '["OFFICE"]'::jsonb, '办公空间使用的书籍与资料柜', 57),
('OFFICE_CREDENZA', '办公边柜', 'OF', 'OF', '["班台副柜","办公矮柜"]'::jsonb, '["OFFICE"]'::jsonb, '与办公桌或会议区配套的低柜', 58),
('DINING_TABLE', '餐桌', 'DT', 'DT', '["家用餐桌","饭桌"]'::jsonb, '["DINING_ROOM"]'::jsonb, '常规家用或商用用餐桌', 59),
('ROUND_DINING_TABLE', '圆餐桌', 'DT', 'DT', '["圆桌","圆形饭桌"]'::jsonb, '["DINING_ROOM"]'::jsonb, '台面为圆形的餐桌', 60),
('EXTENDABLE_DINING_TABLE', '伸缩餐桌', 'DT', 'DT', '["可延长餐桌","拉伸桌"]'::jsonb, '["DINING_ROOM"]'::jsonb, '台面可通过拉伸、翻板等方式扩展的餐桌', 61),
('BANQUET_TABLE', '宴会桌', 'DT', 'DT', '["宴会长桌","酒店餐桌"]'::jsonb, '["BANQUET_HALL","DINING_ROOM"]'::jsonb, '宴会与酒店多人就餐使用的桌台', 62),
('BAR_TABLE', '吧台桌', 'DT', 'DT', '["高脚桌","吧桌"]'::jsonb, '["BAR","DINING_ROOM"]'::jsonb, '台面高度较高、与吧椅配套的桌台', 63),
('KITCHEN_ISLAND_TABLE', '岛台餐桌', 'DT', 'DT', '["餐岛一体桌","中岛桌"]'::jsonb, '["KITCHEN","DINING_ROOM"]'::jsonb, '与厨房岛台连接或一体化的餐桌', 64),
('UPHOLSTERED_BED', '软包床', 'BD', 'BD', '["布艺床","皮床"]'::jsonb, '["BEDROOM"]'::jsonb, '床头或床体大面积采用软包的床', 65),
('PLATFORM_BED', '平台床', 'BD', 'BD', '["地台床","低平台床"]'::jsonb, '["BEDROOM"]'::jsonb, '床垫承托面较低且床边呈平台形的床', 66),
('STORAGE_BED', '储物床', 'BD', 'BD', '["箱体床","高箱床"]'::jsonb, '["BEDROOM"]'::jsonb, '床下具有上揀或抽屉储物空间的床', 67),
('BUNK_BED', '上下床', 'BD', 'BD', '["双层床","高低床"]'::jsonb, '["KIDS_ROOM","DORMITORY"]'::jsonb, '两个睡眠面上下叠置的床', 68),
('LOFT_BED', '高架床', 'BD', 'BD', '["阁楼床","上床下桌"]'::jsonb, '["KIDS_ROOM","DORMITORY"]'::jsonb, '睡眠面抬高，下方留出桌柜或活动空间的床', 69),
('CANOPY_BED', '四柱床', 'BD', 'BD', '["帷幔床","天蓬床"]'::jsonb, '["BEDROOM"]'::jsonb, '四角立柱向上延伸并可悬挂帷幔的床', 70),
('DAY_BED', '日间床', 'BD', 'BD', '["贵妃床","沙发床榻"]'::jsonb, '["LIVING_ROOM","GUEST_ROOM"]'::jsonb, '白天可坐卧、夜间可睡眠的单人床榻', 71),
('KIDS_BED', '儿童床', 'BD', 'BD', '["小孩床","童床"]'::jsonb, '["KIDS_ROOM"]'::jsonb, '尺寸、护栏或造型为儿童使用设计的床', 72),
('PENDANT_LIGHT', '吊灯', 'LT', 'LT', '["单头吊灯","悬吊灯"]'::jsonb, '["LIVING_ROOM","DINING_ROOM"]'::jsonb, '由吊线或吊杆从顶部悬吊的灯具', 73),
('CHANDELIER', '枝形吊灯', 'LT', 'LT', '["水晶吊灯","多臂吊灯"]'::jsonb, '["LIVING_ROOM","DINING_ROOM"]'::jsonb, '具有多灯臂或装饰性大型悬吊结构的灯具', 74),
('CEILING_LIGHT', '吸顶灯', 'LT', 'LT', '["贴顶灯","半吸顶灯"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '紧贴顶面安装的照明灯具', 75),
('FLOOR_LAMP', '落地灯', 'LT', 'LT', '["立灯","地灯"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '带落地底座与长灯杆的可移动灯具', 76),
('TABLE_LAMP', '台灯', 'LT', 'LT', '["桌灯","床头灯"]'::jsonb, '["STUDY","BEDROOM"]'::jsonb, '放置于桌面或柜面的小型灯具', 77),
('WALL_LIGHT', '壁灯', 'LT', 'LT', '["墙灯","床头壁灯"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '固定在墙面的灯具', 78),
('TRACK_LIGHT', '轨道灯', 'LT', 'LT', '["导轨射灯","磁吸轨道灯"]'::jsonb, '["LIVING_ROOM","COMMERCIAL"]'::jsonb, '灯头安装在条形轨道上的灯具系统', 79),
('RECESSED_LIGHT', '嵌入式灯', 'LT', 'LT', '["筒灯","嵌入射灯"]'::jsonb, '["LIVING_ROOM","COMMERCIAL"]'::jsonb, '灯体嵌入吊顶或墙体、仅露出光口的灯具', 80),
('CLAMP_LIGHT', '夹式灯', 'LT', 'LT', '["夹子灯","夹灯"]'::jsonb, '["STUDY","BEDROOM"]'::jsonb, '通过弹簧夹固定于桌沿或床头的灯具', 81),
('DECORATIVE_LIGHT', '装饰灯', 'LT', 'LT', '["造型灯","艺术灯"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '以造型与氛围装饰为主的灯具', 82),
('WRITING_DESK', '写字台', 'DK', 'DK', '["书桌","写字桌"]'::jsonb, '["STUDY","BEDROOM"]'::jsonb, '以阅读与书写为主的家用桌', 83),
('COMPUTER_DESK', '电脑桌', 'DK', 'DK', '["PC桌","家庭办公桌"]'::jsonb, '["STUDY","BEDROOM"]'::jsonb, '以电脑设备与走线管理为主的书桌', 84),
('CORNER_DESK', '转角书桌', 'DK', 'DK', '["L型书桌","拐角桌"]'::jsonb, '["STUDY","OFFICE"]'::jsonb, '两段工作面构成转角的书桌', 85),
('SECRETARY_DESK', '翻板书桌', 'DK', 'DK', '["秘书柜桌","柜桌"]'::jsonb, '["STUDY","LIVING_ROOM"]'::jsonb, '柜体前板翻下后形成工作面的桌', 86),
('WALL_DESK', '壁挂书桌', 'DK', 'DK', '["悬浮书桌","折叠壁桌"]'::jsonb, '["STUDY","BEDROOM"]'::jsonb, '固定于墙面的悬空或折叠桌', 87),
('SPRING_MATTRESS', '弹簧床垫', 'MT', 'MT', '["弹簧垫","袋装弹簧床垫"]'::jsonb, '["BEDROOM"]'::jsonb, '仅在剖面或商品文字明确时判定的弹簧结构床垫', 88),
('FOAM_MATTRESS', '海绵床垫', 'MT', 'MT', '["泡棉床垫","记忆棉床垫"]'::jsonb, '["BEDROOM"]'::jsonb, '仅在剖面或文字明确时判定的泡棉类床垫', 89),
('LATEX_MATTRESS', '乳胶床垫', 'MT', 'MT', '["天然乳胶垫","乳胶睡垫"]'::jsonb, '["BEDROOM"]'::jsonb, '仅在剖面或文字明确时判定的乳胶床垫', 90),
('HYBRID_MATTRESS', '混合床垫', 'MT', 'MT', '["复合床垫","弹簧海绵混合床垫"]'::jsonb, '["BEDROOM"]'::jsonb, '仅在剖面或文字明确多种承托层组合时判定', 91),
('FOLDING_MATTRESS', '折叠床垫', 'MT', 'MT', '["三折床垫","便携睡垫"]'::jsonb, '["BEDROOM","GUEST_ROOM"]'::jsonb, '具有明显分段折线的可折叠床垫', 92),
('WALL_MIRROR', '壁挂镜', 'MR', 'MR', '["挂墙镜","墙镜"]'::jsonb, '["ENTRYWAY","BATHROOM","BEDROOM"]'::jsonb, '固定在墙面的镜子', 93),
('FLOOR_MIRROR', '落地镜', 'MR', 'MR', '["穿衣镜","全身镜"]'::jsonb, '["BEDROOM","ENTRYWAY"]'::jsonb, '落地摆放或斜靠的全身长镜', 94),
('VANITY_MIRROR', '梳妆镜', 'MR', 'MR', '["化妆镜","台镜"]'::jsonb, '["BEDROOM","BATHROOM"]'::jsonb, '配合梳妆台或台面使用的镜子', 95),
('DECORATIVE_MIRROR', '装饰镜', 'MR', 'MR', '["艺术镜","造型镜"]'::jsonb, '["LIVING_ROOM","ENTRYWAY"]'::jsonb, '以异形、拼组或装饰边框为主的镜子', 96),
('AREA_RUG', '块毯', 'RG', 'RG', '["区域地毯","客厅毯"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '用于覆盖局部地面区域的地毯', 97),
('RUNNER_RUG', '长条毯', 'RG', 'RG', '["走廊毯","走道毯"]'::jsonb, '["HALLWAY","ENTRYWAY"]'::jsonb, '用于走廊或床侧的狭长地毯', 98),
('ROUND_RUG', '圆形地毯', 'RG', 'RG', '["圆毯","圆形块毯"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '外轮廓为圆形的区域地毯', 99),
('OUTDOOR_RUG', '户外地毯', 'RG', 'RG', '["防水地毯","阳台毯"]'::jsonb, '["BALCONY","OUTDOOR"]'::jsonb, '图文明确标注耐候或户外用途的地毯', 100),
('FOLDING_SCREEN', '折屏', 'PD', 'PD', '["折叠屏风","多联屏风"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '多片面板铰接并可折叠的屏风', 101),
('ROOM_DIVIDER', '空间隔断', 'PD', 'PD', '["房间分隔","隔断屏"]'::jsonb, '["LIVING_ROOM","OFFICE"]'::jsonb, '用于划分空间且非柜体的直立分隔', 102),
('SLIDING_PARTITION', '滑动隔断', 'PD', 'PD', '["移动隔墙","推拉隔断"]'::jsonb, '["LIVING_ROOM","OFFICE"]'::jsonb, '面板沿轨道滑动开合的隔断', 103),
('ACOUSTIC_PARTITION', '声学隔断', 'PD', 'PD', '["吸音屏风","降噪隔断"]'::jsonb, '["OFFICE","COMMERCIAL"]'::jsonb, '图文明确具有吸音或降噪性能的隔断', 104),
('DRAPE_CURTAIN', '布艺窗帘', 'CW', 'CW', '["布帘","开合帘"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '沿帘杆或轨道水平开合的布艺帘', 105),
('SHEER_CURTAIN', '纱帘', 'CW', 'CW', '["窗纱帘","透光帘"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '以半透明纱料制成的窗帘', 106),
('ROLLER_BLIND', '卷帘', 'CW', 'CW', '["卷布帘","上卷帘"]'::jsonb, '["STUDY","OFFICE"]'::jsonb, '帘布绕卷管上下收卷的窗饰', 107),
('ROMAN_SHADE', '罗马帘', 'CW', 'CW', '["折叠帘","上收布帘"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '向上收起时形成水平层叠的布帘', 108),
('VENETIAN_BLIND', '百叶帘', 'CW', 'CW', '["横百叶","百叶窗"]'::jsonb, '["STUDY","OFFICE"]'::jsonb, '由多片可调角度水平叶片构成的窗饰', 109),
('CELLULAR_SHADE', '蜂巢帘', 'CW', 'CW', '["风琴帘","蜂窝帘"]'::jsonb, '["BEDROOM","STUDY"]'::jsonb, '截面呈中空蜂巢结构的折叠窗饰', 110)
ON CONFLICT (type_code) DO NOTHING;

-- 扩展品类 A-F Schema；E 维只声明语义，枚举继续复用 material/fabric
INSERT INTO six_dim_schema (category_code, dim_key, label, description, sort_order) VALUES
('DK', 'A', '整体布局/轮廓', '桌体俯视与整体布局', 1),
('DK', 'B', '台面形态', '工作台面的厚薄、层级与构造', 2),
('DK', 'C', '侧部/连接结构', '侧柜、挡板、走线与上架连接', 3),
('DK', 'D', '桌腿/支撑', '桌面以下的承重结构', 4),
('DK', 'E', '表面材质', '统一引用 material/fabric 字典', 5),
('DK', 'F', '收纳/功能', '抽屉、升降、充电、折叠等可见功能', 6),
('MT', 'A', '整体厚度/轮廓', '床垫整体厚度、层级与可见轮廓', 1),
('MT', 'B', '顶面绗缝/表层', '顶面缝线、花纹与可见分区', 2),
('MT', 'C', '边缘工艺', '床垫上下边缘的包边与收口工艺', 3),
('MT', 'D', '侧围结构', '侧围纹理、拼接、提手与拉链结构', 4),
('MT', 'E', '表层材质', '统一引用 material/fabric 字典', 5),
('MT', 'F', '可见功能/结构特征', '仅记录图片或明确商品文字可确认的功能', 6),
('MR', 'A', '镜面整体轮廓', '镜面主体的几何轮廓与组合方式', 1),
('MR', 'B', '边框形态', '边框宽度、层级、包覆与装饰形态', 2),
('MR', 'C', '镜面/边缘工艺', '镜面颜色、分割与磨边、车边等工艺', 3),
('MR', 'D', '安装/支撑', '壁挂、落地、台面、悬挂与嵌墙方式', 4),
('MR', 'E', '边框/主体材质', '统一引用 material/fabric 字典', 5),
('MR', 'F', '附加功能', '灯光、储物、角度调节与智能显示等', 6),
('RG', 'A', '外轮廓', '地毯平面外轮廓与模块组合方式', 1),
('RG', 'B', '图案构成', '毯面主要图案、色块与构图类型', 2),
('RG', 'C', '边缘处理', '直切、包边、锁边、流苏与随形边', 3),
('RG', 'D', '绒高/织造表面', '平织、绒高、圈割结构与立体纹理', 4),
('RG', 'E', '材质', '统一引用 material/fabric 字典', 5),
('RG', 'F', '工艺/功能', '可确认的织造工艺、洗护、耐候与防滑功能', 6),
('PD', 'A', '整体组合形态', '屏风片数、围合、滑动、悬挂与架体形态', 1),
('PD', 'B', '面板结构', '实体板、格栅、镂空、编织、玻璃与声学面', 2),
('PD', 'C', '连接结构', '合页、转轴、插接、轨道与吊线等面板连接', 3),
('PD', 'D', '安装/底座', '落地脚、脚轮、顶地支撑、壁固、吊装与地轨', 4),
('PD', 'E', '表面材质', '统一引用 material/fabric 字典', 5),
('PD', 'F', '附加功能', '折叠、移动、置物、挂衣、吸音、展示与绿植等', 6),
('CW', 'A', '窗饰类型', '开合帘、纱帘、罗马帘、卷帘、百叶等主体类型', 1),
('CW', 'B', '帘头/上部结构', '挂钩、波浪、穿杆、孔环、轨道带与帘盒', 2),
('CW', 'C', '帘身褶型/组合', '单双层、开合方向、波浪褶与分幅拼接', 3),
('CW', 'D', '安装/驱动', '帘杆、壁装/顶装轨道、内装、手动与电动驱动', 4),
('CW', 'E', '面料/主体材质', '统一引用 material/fabric 字典', 5),
('CW', 'F', '遮光/功能', '遮光、隐私、隔热、吸音、电动、阻燃与洗护功能', 6)
ON CONFLICT (category_code, dim_key) DO NOTHING;

-- 六维 A 维度 × DK 书桌/写字台（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_A', 'DK-一字矩形', '一字矩形', 'DK', 1, '["直桌","写字台"]', '俯视为单一直线矩形工作面，无转角延伸'),
('six_dim_A', 'DK-L型转角', 'L型转角', 'DK', 2, '["L桌","拐角书桌"]', '两段桌面垂直或近垂直相接形成转角'),
('six_dim_A', 'DK-双人长桌', '双人长桌', 'DK', 3, '["双人书桌","双工位"]', '桌面明显拉长，可同时布置两个工作位'),
('six_dim_A', 'DK-弧形/曲线', '弧形/曲线', 'DK', 4, '["弧形书桌","曲线桌"]', '桌面外轮廓以连续弧线或曲线构成'),
('six_dim_A', 'DK-窄长壁靠', '窄长壁靠', 'DK', 5, '["窄桌","靠墙桌"]', '桌面深度较小且长边贴墙布置'),
('six_dim_A', 'DK-上架一体', '上架一体', 'DK', 6, '["书架桌","带书架书桌"]', '桌面上方有与桌体连成整体的置物架'),
('six_dim_A', 'DK-柜桌一体', '柜桌一体', 'DK', 7, '["书柜书桌一体","侧柜桌"]', '高柜或侧柜与桌面构成不可分的整体'),
('six_dim_A', 'DK-模块组合', '模块组合', 'DK', 8, '["组合书桌","模块桌"]', '多个可辨识桌、柜或架模块拼接'),
('six_dim_A', 'DK-异形/其他', '异形/其他', 'DK', 9, '["艺术书桌","不规则桌"]', '无法归入以上布局的不规则轮廓')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 B 维度 × DK 书桌/写字台（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_B', 'DK-平板薄面', '平板薄面', 'DK', 1, '["薄台面","极简桌面"]', '侧视桌面为单层薄板，边缘轻薄'),
('six_dim_B', 'DK-厚台面', '厚台面', 'DK', 2, '["厚板桌面","大板桌"]', '侧视台面厚度明显，具有块体感'),
('six_dim_B', 'DK-悬浮台面', '悬浮台面', 'DK', 3, '["漂浮桌面","悬空桌面"]', '台面与下部支撑间有内收或明显缝隙'),
('six_dim_B', 'DK-内嵌/包框台面', '内嵌/包框台面', 'DK', 4, '["嵌板桌面","包边桌面"]', '工作面嵌在可见外框中或被框体包围'),
('six_dim_B', 'DK-双层台面', '双层台面', 'DK', 5, '["上下双层","夹层桌面"]', '可见两层平行台面及中间空隙'),
('six_dim_B', 'DK-抬高层台面', '抬高层台面', 'DK', 6, '["显示器架","抬高层"]', '主桌面上方有局部抬高的第二层板'),
('six_dim_B', 'DK-翻折台面', '翻折台面', 'DK', 7, '["翻板桌","可折桌面"]', '台面有明显铰链、折痕或翻转结构'),
('six_dim_B', 'DK-拼接台面', '拼接台面', 'DK', 8, '["组合桌面","拼板桌面"]', '台面由多块材料或色块拼接，接缝可见'),
('six_dim_B', 'DK-异形/其他', '异形/其他', 'DK', 9, '["不规则台面","艺术桌面"]', '无法归入以上构造的特殊台面')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 C 维度 × DK 书桌/写字台（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_C', 'DK-无明显侧件', '无明显侧件', 'DK', 1, '["无侧板","光身桌"]', '桌面侧部无柜箱、挡板或上架连接件'),
('six_dim_C', 'DK-落地侧板', '落地侧板', 'DK', 2, '["板式侧板","封闭侧板"]', '台面一侧或两侧有直达地面的整板'),
('six_dim_C', 'DK-侧柜/抽屉箱', '侧柜/抽屉箱', 'DK', 3, '["抽屉柜","书桌侧柜"]', '桌面侧下方可见抽屉箱或储物柜体'),
('six_dim_C', 'DK-前挡板', '前挡板', 'DK', 4, '["桌挡","遮腿板"]', '桌面前下方有竖向板面遮挡视线'),
('six_dim_C', 'DK-桌面屏风', '桌面屏风', 'DK', 5, '["桌上隔断","桌屏"]', '台面上方竖立用于分隔的屏风板'),
('six_dim_C', 'DK-走线孔/线盒', '走线孔/线盒', 'DK', 6, '["过线孔","桌面线盒"]', '台面可见圆形过线孔或翻盖式线盒'),
('six_dim_C', 'DK-上架连接', '上架连接', 'DK', 7, '["桌架连接","上置书架"]', '侧部立板或竖杆向上支撑书架'),
('six_dim_C', 'DK-横梁拉杆', '横梁拉杆', 'DK', 8, '["桌下横撑","连接梁"]', '桌腿或侧板之间有可见水平拉杆'),
('six_dim_C', 'DK-异形/其他', '异形/其他', 'DK', 9, '["特殊连接","不规则侧件"]', '无法归入以上类型的侧部结构')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 D 维度 × DK 书桌/写字台（11 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_D', 'DK-四直腿', '四直腿', 'DK', 1, '["四脚桌","直桌腿"]', '桌面下方四角分别由垂直腿支撑'),
('six_dim_D', 'DK-外八/斜腿', '外八/斜腿', 'DK', 2, '["八字腿","A字腿"]', '桌腿自上而下向外倾斜张开'),
('six_dim_D', 'DK-U形/口字框架', 'U形/口字框架', 'DK', 3, '["U形腿","口字桌腿"]', '两侧由金属或木质封闭框架承托'),
('six_dim_D', 'DK-T形底座', 'T形底座', 'DK', 4, '["T字腿","一字横脚"]', '竖向支柱底部连接水平横脚形成T形'),
('six_dim_D', 'DK-板式落地侧板', '板式落地侧板', 'DK', 5, '["板脚","全落地侧板"]', '以宽板从台面直接延伸至地面承重'),
('six_dim_D', 'DK-单侧柜支撑', '单侧柜支撑', 'DK', 6, '["单边柜脚","一侧柜体"]', '一侧以柜体承重，另一侧为桌腿或侧板'),
('six_dim_D', 'DK-双侧柜支撑', '双侧柜支撑', 'DK', 7, '["双柜脚","两侧柜体"]', '桌面两侧均由落地柜体承重'),
('six_dim_D', 'DK-悬浮/壁挂', '悬浮/壁挂', 'DK', 8, '["壁挂书桌","悬空桌"]', '桌面固定于墙体且下方无落地支撑'),
('six_dim_D', 'DK-升降立柱', '升降立柱', 'DK', 9, '["电动升降腿","套筒立柱"]', '可见粗壮套筒式立柱和升降框架'),
('six_dim_D', 'DK-脚轮移动', '脚轮移动', 'DK', 10, '["带轮书桌","移动桌"]', '支撑末端可见脚轮或万向轮'),
('six_dim_D', 'DK-异形/其他', '异形/其他', 'DK', 11, '["艺术底座","特殊桌腿"]', '无法归入以上类型的支撑形态')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 F 维度 × DK 书桌/写字台（12 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_F', 'DK-无功能件', '无功能件', 'DK', 1, '["纯台面","固定式"]', '除基本桌面和支撑外无可见功能构件'),
('six_dim_F', 'DK-抽屉', '抽屉', 'DK', 2, '["带抽书桌","桌斗"]', '台面下方可见可抽拉的抽屉面板'),
('six_dim_F', 'DK-侧柜', '侧柜', 'DK', 3, '["桌边柜","副柜"]', '主桌一侧带门板或抽屉的储物柜'),
('six_dim_F', 'DK-开放格', '开放格', 'DK', 4, '["置物格","开放层板"]', '桌体上或下方有无门开放收纳格'),
('six_dim_F', 'DK-上置书架', '上置书架', 'DK', 5, '["桌上书架","上架"]', '桌面上方连接多层书架或层板'),
('six_dim_F', 'DK-走线管理', '走线管理', 'DK', 6, '["理线架","过线系统"]', '可见线盒、线槽、穿线孔或桌下理线架'),
('six_dim_F', 'DK-升降', '升降', 'DK', 7, '["电动升降","手摇升降"]', '可见升降立柱、控制器或手摇机构'),
('six_dim_F', 'DK-折叠', '折叠', 'DK', 8, '["折叠书桌","收折桌"]', '桌腿或桌面具有可见铰链与收折节点'),
('six_dim_F', 'DK-插座/USB/无线充电', '插座/USB/无线充电', 'DK', 9, '["桌面插座","无线充"]', '台面可见电源、USB接口或无线充电标识'),
('six_dim_F', 'DK-键盘托', '键盘托', 'DK', 10, '["键盘架","抽拉键盘板"]', '台面下方有窄长可抽拉托板'),
('six_dim_F', 'DK-脚轮', '脚轮', 'DK', 11, '["万向轮","移动轮"]', '桌体底部可见用于移动的轮体'),
('six_dim_F', 'DK-异形/其他', '异形/其他', 'DK', 12, '["其他桌体功能","特殊功能"]', '无法归入以上类型的可见功能')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 A 维度 × MT 床垫（8 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_A', 'MT-薄垫型', '薄垫型', 'MT', 1, '["薄垫","榻榻米垫"]', '整体厚度较小，侧视呈薄片状'),
('six_dim_A', 'MT-标准厚度', '标准厚度', 'MT', 2, '["常规床垫","标准床垫"]', '整体为常规单层矩形厚度，无额外顶层'),
('six_dim_A', 'MT-厚垫型', '厚垫型', 'MT', 3, '["厚床垫","加厚床垫"]', '侧围高度明显较大，呈厚重块体'),
('six_dim_A', 'MT-双层/加厚舒适层', '双层/加厚舒适层', 'MT', 4, '["双层床垫","舒适层"]', '侧视可见上下两层或加厚顶层分界'),
('six_dim_A', 'MT-枕顶型', '枕顶型', 'MT', 5, '["pillow top","欧式枕顶"]', '床垫顶部有一层边缘独立鼓起的枕形舒适层'),
('six_dim_A', 'MT-折叠型', '折叠型', 'MT', 6, '["三折垫","折叠床垫"]', '垫体有明显横向折线并可分段叠合'),
('six_dim_A', 'MT-分体组合型', '分体组合型', 'MT', 7, '["组合床垫","分体垫"]', '由两块以上独立垫体并置或叠置组成'),
('six_dim_A', 'MT-异形/其他', '异形/其他', 'MT', 8, '["不规则床垫","特殊垫体"]', '无法归入以上厚度轮廓的特殊形态')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 B 维度 × MT 床垫（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_B', 'MT-光面', '光面', 'MT', 1, '["素面顶层","无绗缝"]', '顶面平整，无明显装饰性缝线或分区'),
('six_dim_B', 'MT-菱形绗缝', '菱形绗缝', 'MT', 2, '["钻石格","菱格绗缝"]', '顶面缝线交叉形成连续菱形网格'),
('six_dim_B', 'MT-方格绗缝', '方格绗缝', 'MT', 3, '["棋盘格","方格车线"]', '顶面经纬缝线形成规则方格'),
('six_dim_B', 'MT-横条绗缝', '横条绗缝', 'MT', 4, '["横向车线","条纹绗缝"]', '顶面以平行横向缝线分区'),
('six_dim_B', 'MT-波浪绗缝', '波浪绗缝', 'MT', 5, '["水波纹","曲线绗缝"]', '顶面缝线呈连续波浪或曲线'),
('six_dim_B', 'MT-深拉点/拉扣', '深拉点/拉扣', 'MT', 6, '["拉点","纽扣绗缝"]', '顶面有规则深凹点及放射褶皱'),
('six_dim_B', 'MT-立体花纹针织', '立体花纹针织', 'MT', 7, '["针织花纹","提花面"]', '面料本身具有凸起针织或提花纹理'),
('six_dim_B', 'MT-分区纹理', '分区纹理', 'MT', 8, '["七区纹理","功能分区"]', '顶面用不同缝线或纹理明确分成多个区域'),
('six_dim_B', 'MT-异形/其他', '异形/其他', 'MT', 9, '["特殊绗缝","不规则表层"]', '无法归入以上类型的顶面纹理')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 C 维度 × MT 床垫（7 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_C', 'MT-直边', '直边', 'MT', 1, '["平直围边","素边"]', '顶面与侧围以平直缝线收边'),
('six_dim_C', 'MT-滚边/包边', '滚边/包边', 'MT', 2, '["围边","嵌线包边"]', '上下边缘有连续凸起滚条'),
('six_dim_C', 'MT-双色撞色包边', '双色撞色包边', 'MT', 3, '["撞色滚边","双色围边"]', '包边颜色与顶面或侧围形成明显反差'),
('six_dim_C', 'MT-加厚围边', '加厚围边', 'MT', 4, '["宽围边","厚边条"]', '边缘有宽厚的加固包边带'),
('six_dim_C', 'MT-圆角包边', '圆角包边', 'MT', 5, '["R角围边","圆弧边"]', '床垫四角圆滑过渡，包边沿圆角连续延伸'),
('six_dim_C', 'MT-双层围边', '双层围边', 'MT', 6, '["双道滚边","双线包边"]', '边缘可见上下两道平行围边'),
('six_dim_C', 'MT-异形/其他', '异形/其他', 'MT', 7, '["特殊围边","不规则收边"]', '无法归入以上类型的边缘工艺')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 D 维度 × MT 床垫（8 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_D', 'MT-素面侧围', '素面侧围', 'MT', 1, '["光面侧边","无装饰侧围"]', '侧围为单色平整面，无明显缝线或功能件'),
('six_dim_D', 'MT-绗缝侧围', '绗缝侧围', 'MT', 2, '["侧边车线","绗缝围边"]', '侧围可见规则格纹或条纹缝线'),
('six_dim_D', 'MT-透气网侧围', '透气网侧围', 'MT', 3, '["透气网布","3D网围边"]', '侧围有明显网眼或网格透气带'),
('six_dim_D', 'MT-分段拼接侧围', '分段拼接侧围', 'MT', 4, '["拼色侧围","分区侧边"]', '侧围由不同材料、颜色或纹理分段拼接'),
('six_dim_D', 'MT-带提手', '带提手', 'MT', 5, '["搬运提手","侧提带"]', '侧围可见缝制或固定的环形提手'),
('six_dim_D', 'MT-带拉链外套', '带拉链外套', 'MT', 6, '["可拆拉链","拉链套"]', '侧围或底边可见连续拉链轨迹'),
('six_dim_D', 'MT-加固护边', '加固护边', 'MT', 7, '["护边条","围护加固"]', '侧围边缘有额外加宽或加厚的支撑带'),
('six_dim_D', 'MT-异形/其他', '异形/其他', 'MT', 8, '["特殊侧围","不规则侧边"]', '无法归入以上类型的侧围结构')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 F 维度 × MT 床垫（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_F', 'MT-无明显功能', '无明显功能', 'MT', 1, '["常规床垫","无附加功能"]', '外观与文字中无法确认其他功能结构'),
('six_dim_F', 'MT-可拆洗外套', '可拆洗外套', 'MT', 2, '["可脱卸外套","可洗床垫套"]', '可见环绕拉链或文字明确说明外套可拆洗'),
('six_dim_F', 'MT-可折叠', '可折叠', 'MT', 3, '["三折","收折垫"]', '垫体有可折叠分段和明显软性铰接线'),
('six_dim_F', 'MT-双面可用', '双面可用', 'MT', 4, '["双面睡","两面用"]', '只在图文明确展示两面不同或标注双面可用时判定'),
('six_dim_F', 'MT-独立舒适层/薄垫组合', '独立舒适层/薄垫组合', 'MT', 5, '["子母垫","独立顶垫"]', '主床垫上方有可分离的独立薄垫层'),
('six_dim_F', 'MT-分区标识', '分区标识', 'MT', 6, '["七区承托","分区线"]', '顶面图形或文字明确标出不同承托区'),
('six_dim_F', 'MT-防滑底面', '防滑底面', 'MT', 7, '["防滑布","防移位底"]', '底面可见防滑胶点、粗糙纹理或文字标注'),
('six_dim_F', 'MT-卷包/压缩包装', '卷包/压缩包装', 'MT', 8, '["卷装床垫","压缩床垫"]', '图文明确展示床垫卷曲或真空压缩包装'),
('six_dim_F', 'MT-异形/其他', '异形/其他', 'MT', 9, '["其他床垫功能","特殊功能"]', '只记录图片或明确商品文字可确认的其他功能')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 A 维度 × MR 镜子（10 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_A', 'MR-圆形', '圆形', 'MR', 1, '["圆镜","正圆镜"]', '镜面外轮廓为正圆或近圆'),
('six_dim_A', 'MR-椭圆形', '椭圆形', 'MR', 2, '["椭圆镜","蛋形镜"]', '镜面呈规则椭圆轮廓'),
('six_dim_A', 'MR-矩形', '矩形', 'MR', 3, '["长方镜","方镜"]', '镜面为直边四边形，长宽可不等'),
('six_dim_A', 'MR-拱形', '拱形', 'MR', 4, '["拱门镜","圆拱镜"]', '下部为直边，顶部呈半圆或拱门形'),
('six_dim_A', 'MR-跑道形', '跑道形', 'MR', 5, '["胶囊镜","长圆镜"]', '两端半圆与中间直边构成拉长轮廓'),
('six_dim_A', 'MR-水滴形', '水滴形', 'MR', 6, '["滴水镜","梨形镜"]', '轮廓一端收尖、另一端圆润'),
('six_dim_A', 'MR-不规则有机形', '不规则有机形', 'MR', 7, '["异形镜","云朵镜"]', '镜面边界为非对称自由曲线'),
('six_dim_A', 'MR-全身长镜', '全身长镜', 'MR', 8, '["穿衣镜","落地长镜"]', '镜面高度明显大于宽度，可映照全身'),
('six_dim_A', 'MR-多片组合', '多片组合', 'MR', 9, '["拼镜","组合装饰镜"]', '由两片以上独立镜面拼组成整体'),
('six_dim_A', 'MR-异形/其他', '异形/其他', 'MR', 10, '["艺术镜","特殊轮廓镜"]', '无法归入以上类型的特殊镜面轮廓')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 B 维度 × MR 镜子（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_B', 'MR-无框', '无框', 'MR', 1, '["裸镜","无边框镜"]', '镜面边缘无可见独立边框'),
('six_dim_B', 'MR-超窄框', '超窄框', 'MR', 2, '["极窄框","线框镜"]', '边框宽度极小，正视仅呈细线'),
('six_dim_B', 'MR-标准细框', '标准细框', 'MR', 3, '["细边框","常规框"]', '边框清晰可见但不占据大面积'),
('six_dim_B', 'MR-宽框', '宽框', 'MR', 4, '["粗框","厚边框"]', '边框宽度明显，形成较大装饰面'),
('six_dim_B', 'MR-双层框', '双层框', 'MR', 5, '["内外双框","双圈框"]', '镜面外周可见两道分离或叠层框线'),
('six_dim_B', 'MR-包覆软框', '包覆软框', 'MR', 6, '["软包镜框","皮革包框"]', '边框表面有织物或皮革包覆的软质感'),
('six_dim_B', 'MR-雕塑异形框', '雕塑异形框', 'MR', 7, '["造型镜框","雕塑框"]', '边框以不规则立体块面或雕塑形态构成'),
('six_dim_B', 'MR-装饰雕花框', '装饰雕花框', 'MR', 8, '["雕花镜框","花纹框"]', '边框表面有清晰浮雕、雕花或古典纹样'),
('six_dim_B', 'MR-异形/其他', '异形/其他', 'MR', 9, '["特殊镜框","其他框型"]', '无法归入以上类型的边框形态')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 C 维度 × MR 镜子（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_C', 'MR-平面直边', '平面直边', 'MR', 1, '["平镜","直切边"]', '镜面平整，边缘无可见斜面或分割'),
('six_dim_C', 'MR-磨边', '磨边', 'MR', 2, '["精磨边","抛光边"]', '镜面边缘可见窄小均匀的磨光带'),
('six_dim_C', 'MR-斜边/车边', '斜边/车边', 'MR', 3, '["斜切镜","车边镜"]', '镜面四周有明显斜面反光边'),
('six_dim_C', 'MR-圆角', '圆角', 'MR', 4, '["R角镜","圆角边"]', '镜面角部以圆弧过渡而非尖角'),
('six_dim_C', 'MR-烟熏/灰镜', '烟熏/灰镜', 'MR', 5, '["灰镜","烟熏镜"]', '镜面整体呈灰色或烟熏色反射'),
('six_dim_C', 'MR-茶色镜', '茶色镜', 'MR', 6, '["茶镜","棕镜"]', '镜面整体呈茶棕色反射'),
('six_dim_C', 'MR-分割拼镜', '分割拼镜', 'MR', 7, '["分格镜","几何拼镜"]', '镜面由多块平面镜以可见接缝拼接'),
('six_dim_C', 'MR-波纹/艺术镜面', '波纹/艺术镜面', 'MR', 8, '["波浪镜","纹理镜"]', '镜面本身有起伏、波纹或故意变形反射'),
('six_dim_C', 'MR-异形/其他', '异形/其他', 'MR', 9, '["特殊镜面工艺","其他边缘"]', '无法归入以上类型的镜面或边缘工艺')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 D 维度 × MR 镜子（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_D', 'MR-壁挂', '壁挂', 'MR', 1, '["挂墙镜","墙镜"]', '镜体贴墙固定，不触地且无独立支架'),
('six_dim_D', 'MR-落地斜靠', '落地斜靠', 'MR', 2, '["斜靠镜","靠墙镜"]', '长镜底部落地，上部直接斜靠墙面'),
('six_dim_D', 'MR-落地自立支架', '落地自立支架', 'MR', 3, '["支架穿衣镜","落地镜架"]', '镜后或两侧有独立支架使其自立'),
('six_dim_D', 'MR-台面摆放', '台面摆放', 'MR', 4, '["台镜","桌面镜"]', '小尺寸镜体通过底座放置在台面'),
('six_dim_D', 'MR-旋转支架', '旋转支架', 'MR', 5, '["翻转镜","旋转台镜"]', '镜体两侧或中轴可见转轴支撑'),
('six_dim_D', 'MR-吊带悬挂', '吊带悬挂', 'MR', 6, '["皮带挂镜","绳挂镜"]', '镜体上方以皮带、绳或链条悬挂'),
('six_dim_D', 'MR-柜体一体', '柜体一体', 'MR', 7, '["镜柜一体","柜门镜"]', '镜面与柜门、收纳柜或梳妆台连成整体'),
('six_dim_D', 'MR-嵌墙', '嵌墙', 'MR', 8, '["嵌入式镜","入墙镜"]', '镜面边缘与墙面平齐或嵌入墙体槽内'),
('six_dim_D', 'MR-异形/其他', '异形/其他', 'MR', 9, '["特殊安装镜","其他支撑"]', '无法归入以上类型的安装或支撑方式')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 F 维度 × MR 镜子（10 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_F', 'MR-无功能', '无功能', 'MR', 1, '["普通镜","纯镜面"]', '除反射成像外无其他可见功能构件'),
('six_dim_F', 'MR-环形灯带', '环形灯带', 'MR', 2, '["环形发光","一圈灯带"]', '镜面周边有连续环形发光带'),
('six_dim_F', 'MR-背光', '背光', 'MR', 3, '["镜后灯","背面发光"]', '光线从镜体背后投向墙面形成光晕'),
('six_dim_F', 'MR-前置灯', '前置灯', 'MR', 4, '["镜前灯","正面灯条"]', '镜体正面或边框上有独立灯头或灯条'),
('six_dim_F', 'MR-储物', '储物', 'MR', 5, '["镜柜","带置物架镜"]', '镜后或侧部有柜体、层板或置物格'),
('six_dim_F', 'MR-可调角度', '可调角度', 'MR', 6, '["俯仰调节","角度可调"]', '可见转轴、紧固旋钮或多档俯仰结构'),
('six_dim_F', 'MR-双面旋转', '双面旋转', 'MR', 7, '["双面镜","翻转双面镜"]', '镜体可绕轴翻转且两面均为镜面'),
('six_dim_F', 'MR-放大镜', '放大镜', 'MR', 8, '["倍率镜","局部放大镜"]', '主镜上或侧部有独立小型放大镜'),
('six_dim_F', 'MR-智能显示', '智能显示', 'MR', 9, '["智能镜","时钟温度显示"]', '镜面可见数字、图标或信息显示区'),
('six_dim_F', 'MR-异形/其他', '异形/其他', 'MR', 10, '["其他镜面功能","特殊功能镜"]', '无法归入以上类型的可见附加功能')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 A 维度 × RG 地毯（8 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_A', 'RG-矩形', '矩形', 'RG', 1, '["长方形地毯","方边毯"]', '外轮廓为四条直边的长方形'),
('six_dim_A', 'RG-方形', '方形', 'RG', 2, '["正方形地毯","方毯"]', '外轮廓为四边近等长的正方形'),
('six_dim_A', 'RG-圆形', '圆形', 'RG', 3, '["圆毯","正圆地毯"]', '外轮廓为正圆或近圆'),
('six_dim_A', 'RG-椭圆形', '椭圆形', 'RG', 4, '["椭圆毯","蛋形地毯"]', '外轮廓为规则椭圆'),
('six_dim_A', 'RG-长条跑道/走廊毯', '长条跑道/走廊毯', 'RG', 5, '["走廊毯","长条毯"]', '轮廓狭长，长度明显大于宽度'),
('six_dim_A', 'RG-不规则有机形', '不规则有机形', 'RG', 6, '["异形地毯","有机形毯"]', '边界为非对称自由曲线'),
('six_dim_A', 'RG-拼接模块', '拼接模块', 'RG', 7, '["方块毯","模块地毯"]', '由多块边界清晰的小毯块拼接'),
('six_dim_A', 'RG-异形/其他', '异形/其他', 'RG', 8, '["特殊轮廓毯","其他形状地毯"]', '无法归入以上类型的特殊轮廓')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 B 维度 × RG 地毯（11 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_B', 'RG-纯色', '纯色', 'RG', 1, '["素色毯","无图案"]', '毯面整体为单一色相或近似色调'),
('six_dim_B', 'RG-几何', '几何', 'RG', 2, '["几何图案","方圆纹样"]', '由直线、圆形、多边形等规则图形构成'),
('six_dim_B', 'RG-条纹', '条纹', 'RG', 3, '["横条毯","竖条毯"]', '毯面以平行或交叉条带为主'),
('six_dim_B', 'RG-抽象', '抽象', 'RG', 4, '["抽象画毯","抽象纹样"]', '图案为非具象的自由色彩与形状组合'),
('six_dim_B', 'RG-色块拼接', '色块拼接', 'RG', 5, '["拼色毯","色块毯"]', '多个边界清晰的大面积色块拼组'),
('six_dim_B', 'RG-渐变', '渐变', 'RG', 6, '["渐变毯","晕染毯"]', '颜色明度或色相在毯面连续过渡'),
('six_dim_B', 'RG-植物/花卉', '植物/花卉', 'RG', 7, '["花卉毯","叶片图案"]', '图案以花朵、枝叶或植物形态为主'),
('six_dim_B', 'RG-东方/古典纹样', '东方/古典纹样', 'RG', 8, '["传统纹样","波斯纹"]', '毯面以中轴对称花纹、回纹或古典章法组成'),
('six_dim_B', 'RG-仿旧纹样', '仿旧纹样', 'RG', 9, '["做旧毯","褪色毯"]', '图案带有故意磨损、断续或褪色效果'),
('six_dim_B', 'RG-无规则艺术纹样', '无规则艺术纹样', 'RG', 10, '["艺术喷洒","自由纹样"]', '图案无明显重复单元，呈自由艺术构图'),
('six_dim_B', 'RG-异形/其他', '异形/其他', 'RG', 11, '["其他地毯图案","特殊纹样"]', '无法归入以上类型的图案构成')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 C 维度 × RG 地毯（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_C', 'RG-直切边', '直切边', 'RG', 1, '["平切边","无装饰边"]', '毯边被平直裁切，无额外装饰'),
('six_dim_C', 'RG-包边', '包边', 'RG', 2, '["包边带","嵌条边"]', '毯边被独立布带或材料条包覆'),
('six_dim_C', 'RG-锁边', '锁边', 'RG', 3, '["机锁边","绕线边"]', '边缘可见密集绕线或锁线针脚'),
('six_dim_C', 'RG-流苏', '流苏', 'RG', 4, '["流苏边","穗子边"]', '毯体端部垂下成排细线束'),
('six_dim_C', 'RG-穗边', '穗边', 'RG', 5, '["粗穗边","手工穗子"]', '边缘有较粗、较短的结绳或穗状束'),
('six_dim_C', 'RG-波浪/花边', '波浪/花边', 'RG', 6, '["波浪边","花瓣边"]', '毯边以规则曲线或花瓣轮廓起伏'),
('six_dim_C', 'RG-自然毛边', '自然毛边', 'RG', 7, '["毛边","未裁切边"]', '边缘保留纤维或毛料自然散开状态'),
('six_dim_C', 'RG-不规则随形边', '不规则随形边', 'RG', 8, '["随形边","有机曲线边"]', '边缘跟随不规则图形连续变化'),
('six_dim_C', 'RG-异形/其他', '异形/其他', 'RG', 9, '["特殊毯边","其他收边"]', '无法归入以上类型的边缘处理')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 D 维度 × RG 地毯（11 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_D', 'RG-平织', '平织', 'RG', 1, '["无绒平织","平面编织"]', '毯面几乎无竖起绒毛，经纬结构清晰'),
('six_dim_D', 'RG-短绒', '短绒', 'RG', 2, '["低绒","短毛毯"]', '绒毛竖起高度较小，表面紧密'),
('six_dim_D', 'RG-中绒', '中绒', 'RG', 3, '["中毛毯","常规绒高"]', '绒毛高度中等，可见柔软但不呈长毛'),
('six_dim_D', 'RG-高绒', '高绒', 'RG', 4, '["厚绒","高毛毯"]', '绒毛明显较高，手感外观蓬松厚实'),
('six_dim_D', 'RG-长毛/Shaggy', '长毛/Shaggy', 'RG', 5, '["Shaggy毯","长绒毯"]', '绒线长且自由倒伏，表面呈明显长毛感'),
('six_dim_D', 'RG-圈绒', '圈绒', 'RG', 6, '["圈毛","毛圈毯"]', '毯面纱线保持闭合环圈，可见小圈结构'),
('six_dim_D', 'RG-割绒', '割绒', 'RG', 7, '["剪绒","平剪绒"]', '纱圈被割开形成整齐竖立绒头'),
('six_dim_D', 'RG-圈割结合', '圈割结合', 'RG', 8, '["混合绒","圈绒割绒"]', '毯面同时可见环圈和割开绒头'),
('six_dim_D', 'RG-编织/辫织', '编织/辫织', 'RG', 9, '["粗编毯","辫绳毯"]', '粗纱或带状材料以编织、辫织结构构成毯面'),
('six_dim_D', 'RG-高低立体纹理', '高低立体纹理', 'RG', 10, '["高低绒","浮雕毯面"]', '不同区域绒高有明显高低差形成立体图案'),
('six_dim_D', 'RG-异形/其他', '异形/其他', 'RG', 11, '["特殊织造表面","其他绒面"]', '无法归入以上类型的织造表面')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 F 维度 × RG 地毯（10 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_F', 'RG-常规固定', '常规固定', 'RG', 1, '["常规毯","无明显工艺功能"]', '图片与文字无法确认特殊工艺或功能'),
('six_dim_F', 'RG-手工簇绒', '手工簇绒', 'RG', 2, '["手工枪刺","簇绒毯"]', '只在背面、工艺图或商品文字明确时判定手工簇绒'),
('six_dim_F', 'RG-手工打结', '手工打结', 'RG', 3, '["手工结毯","手工结织"]', '只在结构细节或文字明确可见手工打结时判定'),
('six_dim_F', 'RG-机织', '机织', 'RG', 4, '["机器织造","机制毯"]', '只在商品文字或工艺标注明确时判定机织'),
('six_dim_F', 'RG-可机洗', '可机洗', 'RG', 5, '["机洗地毯","洗衣机可洗"]', '商品图文明确出现可机洗标识或说明'),
('six_dim_F', 'RG-户外耐候', '户外耐候', 'RG', 6, '["户外毯","防晒防水"]', '商品图文明确标注户外、耐候或防晒用途'),
('six_dim_F', 'RG-防滑底', '防滑底', 'RG', 7, '["止滑背胶","防滑背面"]', '背面可见胶点、橡胶层或防滑纹理'),
('six_dim_F', 'RG-双面可用', '双面可用', 'RG', 8, '["双面毯","正反两用"]', '两面均完整展示或文字明确标注可翻面使用'),
('six_dim_F', 'RG-拼块组合', '拼块组合', 'RG', 9, '["地毯方块","可替换毯块"]', '由标准化小块组合，块间边界可辨识'),
('six_dim_F', 'RG-异形/其他', '异形/其他', 'RG', 10, '["其他地毯工艺","特殊功能毯"]', '只记录图片或明确文字可确认的其他工艺功能')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 A 维度 × PD 屏风/隔断（10 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_A', 'PD-单片直立', '单片直立', 'PD', 1, '["单片屏风","直立隔断"]', '由一片独立面板直立构成'),
('six_dim_A', 'PD-双片折屏', '双片折屏', 'PD', 2, '["两折屏风","双联屏"]', '两片面板以一道铰接线折叠'),
('six_dim_A', 'PD-三片折屏', '三片折屏', 'PD', 3, '["三折屏风","三联屏"]', '三片面板以两道铰接线连接'),
('six_dim_A', 'PD-多片折屏', '多片折屏', 'PD', 4, '["多折屏风","多联屏"]', '四片以上面板连续铰接并可折叠'),
('six_dim_A', 'PD-弧形围合', '弧形围合', 'PD', 5, '["弧形屏风","环抱隔断"]', '整体以弧线或多片折线形成围合'),
('six_dim_A', 'PD-模块拼接', '模块拼接', 'PD', 6, '["组合隔断","模块屏"]', '多个标准面板或单元可重复拼接'),
('six_dim_A', 'PD-滑动隔断', '滑动隔断', 'PD', 7, '["移动隔断","推拉屏"]', '面板沿水平轨道滑动开合'),
('six_dim_A', 'PD-悬挂隔断', '悬挂隔断', 'PD', 8, '["吊挂屏","悬空隔断"]', '隔断从顶部吊挂，底部不落地'),
('six_dim_A', 'PD-架体隔断', '架体隔断', 'PD', 9, '["置物架隔断","格架屏"]', '以开放架体或格子架作为分隔主体'),
('six_dim_A', 'PD-异形/其他', '异形/其他', 'PD', 10, '["艺术隔断","特殊屏风"]', '无法归入以上组合形态的特殊轮廓')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 B 维度 × PD 屏风/隔断（10 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_B', 'PD-实体板', '实体板', 'PD', 1, '["实心屏板","封闭面板"]', '面板为不透空的连续实体表面'),
('six_dim_B', 'PD-格栅', '格栅', 'PD', 2, '["竖格栅","条栅隔断"]', '由平行条杆排列构成，条间可透视'),
('six_dim_B', 'PD-镂空花格', '镂空花格', 'PD', 3, '["花格屏风","雕花隔断"]', '板面开有规则或装饰性镂空图案'),
('six_dim_B', 'PD-藤编/绳编', '藤编/绳编', 'PD', 4, '["藤编屏","绳网隔断"]', '面板由藤条、绳或编带交叉编织'),
('six_dim_B', 'PD-玻璃', '玻璃', 'PD', 5, '["玻璃隔断","透明屏"]', '主要面板为透明、半透明或磨砂玻璃'),
('six_dim_B', 'PD-布艺软包', '布艺软包', 'PD', 6, '["软包屏风","布面隔断"]', '面板表面有织物包覆和可见填充厚度'),
('six_dim_B', 'PD-声学吸音面', '声学吸音面', 'PD', 7, '["吸音屏","声学隔断"]', '面板有声学毛毡、微孔或商品文字明确标注吸音'),
('six_dim_B', 'PD-开放置物架', '开放置物架', 'PD', 8, '["层架隔断","书架屏风"]', '主体为多层开放格，可放置物品'),
('six_dim_B', 'PD-混合拼接', '混合拼接', 'PD', 9, '["多材料屏","实虚组合"]', '同一面板明显由两种以上结构或材料分区拼接'),
('six_dim_B', 'PD-异形/其他', '异形/其他', 'PD', 10, '["特殊面板","其他屏面"]', '无法归入以上类型的面板结构')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 C 维度 × PD 屏风/隔断（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_C', 'PD-无连接单片', '无连接单片', 'PD', 1, '["单片无铰","独立屏"]', '单片面板无与其他面板的可见连接件'),
('six_dim_C', 'PD-合页铰接', '合页铰接', 'PD', 2, '["合页折屏","金属合页"]', '相邻面板以可见合页连接并可折叠'),
('six_dim_C', 'PD-转轴连接', '转轴连接', 'PD', 3, '["立轴连接","旋转轴"]', '面板沿竖向转轴转动，轴线结构可见'),
('six_dim_C', 'PD-插接模块', '插接模块', 'PD', 4, '["卡槽拼接","插槽连接"]', '模块通过槽口、卡扣或插销可拆拼接'),
('six_dim_C', 'PD-金属连接杆', '金属连接杆', 'PD', 5, '["连接管","金属拉杆"]', '面板之间以外露金属杆或管件连接'),
('six_dim_C', 'PD-轨道连接', '轨道连接', 'PD', 6, '["滑轨隔断","导轨连接"]', '面板顶部或底部嵌入连续滑轨'),
('six_dim_C', 'PD-绳索/吊线连接', '绳索/吊线连接', 'PD', 7, '["吊线屏","绳挂隔断"]', '独立单元由绳索、钢索或吊线串联'),
('six_dim_C', 'PD-隐藏连接', '隐藏连接', 'PD', 8, '["无缝连接","暗铰"]', '面板间可活动或拼接，但正面看不到明显连接件'),
('six_dim_C', 'PD-异形/其他', '异形/其他', 'PD', 9, '["特殊连接","其他铰接"]', '无法归入以上类型的连接结构')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 D 维度 × PD 屏风/隔断（10 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_D', 'PD-落地宽脚', '落地宽脚', 'PD', 1, '["宽底座","板式底脚"]', '面板底部有明显加宽的落地脚或底板'),
('six_dim_D', 'PD-T形脚', 'T形脚', 'PD', 2, '["T字底脚","一字横脚"]', '竖向支柱底部连接水平横脚形成T形'),
('six_dim_D', 'PD-金属框架脚', '金属框架脚', 'PD', 3, '["金属底架","管状框架"]', '底部由金属管或扁钢框架承托'),
('six_dim_D', 'PD-脚轮移动', '脚轮移动', 'PD', 4, '["移动屏风","带轮隔断"]', '底座下方可见脚轮或万向轮'),
('six_dim_D', 'PD-顶天立地', '顶天立地', 'PD', 5, '["顶地撑","张紧立柱"]', '立柱同时抵住地面与顶面形成张紧固定'),
('six_dim_D', 'PD-墙面固定', '墙面固定', 'PD', 6, '["靠墙隔断","壁装屏"]', '隔断通过连接件固定在墙面'),
('six_dim_D', 'PD-吊顶悬挂', '吊顶悬挂', 'PD', 7, '["顶吊屏","吊挂隔断"]', '隔断重量主要由顶部吊件承担'),
('six_dim_D', 'PD-地轨滑动', '地轨滑动', 'PD', 8, '["地轨屏","推拉地轨"]', '底部嵌入或运行于地面导轨'),
('six_dim_D', 'PD-无明显底座', '无明显底座', 'PD', 9, '["隐藏底座","无脚屏"]', '正视无法看到独立脚、底板或轨道'),
('six_dim_D', 'PD-异形/其他', '异形/其他', 'PD', 10, '["特殊安装","其他底座"]', '无法归入以上类型的安装或底座形态')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 F 维度 × PD 屏风/隔断（10 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_F', 'PD-无功能', '无功能', 'PD', 1, '["纯分隔","普通屏风"]', '除空间分隔外无其他可见功能构件'),
('six_dim_F', 'PD-可折叠', '可折叠', 'PD', 2, '["折屏","可收折屏风"]', '多片面板可沿铰接点折叠收拢'),
('six_dim_F', 'PD-可移动', '可移动', 'PD', 3, '["移动隔断","带轮屏"]', '可见脚轮、手柄或其他专用移动结构'),
('six_dim_F', 'PD-置物/书架', '置物/书架', 'PD', 4, '["置物屏风","书架隔断"]', '隔断上设有可放物的层板或开放格'),
('six_dim_F', 'PD-挂衣', '挂衣', 'PD', 5, '["挂衣隔断","衣钩屏"]', '面板或架体上可见挂钩、挂杆或衣帽架'),
('six_dim_F', 'PD-声学吸音', '声学吸音', 'PD', 6, '["吸音隔断","降噪屏"]', '只在吸音材料结构可见或商品文字明确时判定'),
('six_dim_F', 'PD-白板/展示', '白板/展示', 'PD', 7, '["书写屏","展板隔断"]', '面板可书写、磁吸或张贴展示内容'),
('six_dim_F', 'PD-绿植组合', '绿植组合', 'PD', 8, '["植物隔断","花槽屏风"]', '隔断与花槽、种植盒或绿植支架连成整体'),
('six_dim_F', 'PD-灯光', '灯光', 'PD', 9, '["发光隔断","灯带屏风"]', '面板或框架可见集成灯带或发光模块'),
('six_dim_F', 'PD-异形/其他', '异形/其他', 'PD', 10, '["其他隔断功能","特殊功能屏"]', '无法归入以上类型的可见附加功能')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 A 维度 × CW 窗帘/窗饰（10 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_A', 'CW-布艺开合帘', '布艺开合帘', 'CW', 1, '["布帘","对开帘"]', '织物帘身沿水平轨道或帘杆左右开合'),
('six_dim_A', 'CW-纱帘', '纱帘', 'CW', 2, '["窗纱","透光纱帘"]', '帘身轻薄半透明，可透光且可见细密网纹'),
('six_dim_A', 'CW-罗马帘', '罗马帘', 'CW', 3, '["折叠罗马帘","上收布帘"]', '帘身向上收起时形成水平层叠'),
('six_dim_A', 'CW-卷帘', '卷帘', 'CW', 4, '["上卷帘","滚轴帘"]', '平整帘布绕顶部卷管上下收卷'),
('six_dim_A', 'CW-百叶帘', '百叶帘', 'CW', 5, '["横百叶","百叶窗"]', '多片平行叶片水平排列并可调角度'),
('six_dim_A', 'CW-垂直帘', '垂直帘', 'CW', 6, '["竖百叶","垂直叶片帘"]', '多片竖向长条叶片并排悬挂'),
('six_dim_A', 'CW-蜂巢帘', '蜂巢帘', 'CW', 7, '["风琴帘","蜂窝帘"]', '侧视可见连续中空蜂巢或风琴褶结构'),
('six_dim_A', 'CW-柔纱帘', '柔纱帘', 'CW', 8, '["调光帘","斑马帘"]', '透纱与不透光条带交替，通过错位调光'),
('six_dim_A', 'CW-面板帘', '面板帘', 'CW', 9, '["日式面板帘","滑动布板"]', '多片平整宽幅布板沿多轨水平滑动'),
('six_dim_A', 'CW-异形/其他', '异形/其他', 'CW', 10, '["特殊窗饰","其他帘类"]', '无法归入以上类型的窗口遮挡结构')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 B 维度 × CW 窗帘/窗饰（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_B', 'CW-挂钩打褶', '挂钩打褶', 'CW', 1, '["普通挂钩","打褶帘头"]', '帘布顶部以挂钩固定并形成规则褶皱'),
('six_dim_B', 'CW-四爪/多褶', '四爪/多褶', 'CW', 2, '["四爪钩","多倍褶"]', '每个挂点附近被集中收成四爪或多道立褶'),
('six_dim_B', 'CW-波浪帘', '波浪帘', 'CW', 3, '["S形帘头","蛇形帘"]', '顶部沿轨道形成连续等距S形波浪'),
('six_dim_B', 'CW-穿杆', '穿杆', 'CW', 4, '["杆袋帘","套杆帘"]', '帘布顶部缝成连续套袋，帘杆从中穿过'),
('six_dim_B', 'CW-打孔环', '打孔环', 'CW', 5, '["罗马圈","孔环帘"]', '帘布顶部排列大型金属或塑料环孔'),
('six_dim_B', 'CW-轨道带', '轨道带', 'CW', 6, '["挂轨带","帘头轨带"]', '顶部缝有连续窄带并以滑轮挂接轨道'),
('six_dim_B', 'CW-明装帘头', '明装帘头', 'CW', 7, '["装饰帘头","帘楣"]', '主帘上方有独立可见的短帘或装饰帘楣'),
('six_dim_B', 'CW-盒式帘头', '盒式帘头', 'CW', 8, '["帘盒","窗帘盒"]', '轨道和帘布顶部被硬质盒体遮挡'),
('six_dim_B', 'CW-异形/其他', '异形/其他', 'CW', 9, '["特殊帘头","其他上部结构"]', '无法归入以上类型的帘头或上部构造')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 C 维度 × CW 窗帘/窗饰（8 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_C', 'CW-单层', '单层', 'CW', 1, '["单帘","单层窗帘"]', '窗口只有一层帘身或叶片系统'),
('six_dim_C', 'CW-双层布纱', '双层布纱', 'CW', 2, '["布纱双层","遮光帘加纱帘"]', '同一窗口前后并置遮光布帘与透光纱帘'),
('six_dim_C', 'CW-左右对开', '左右对开', 'CW', 3, '["双开帘","对开窗帘"]', '两幅帘身从中央分开并向左右收拢'),
('six_dim_C', 'CW-单边开合', '单边开合', 'CW', 4, '["单开帘","一侧收帘"]', '整幅帘身统一向左或向右一侧收拢'),
('six_dim_C', 'CW-连续波浪', '连续波浪', 'CW', 5, '["S形褶","等距波形"]', '帘身从顶到底保持连续等距波形褶皱'),
('six_dim_C', 'CW-平面垂落', '平面垂落', 'CW', 6, '["平帘","无褶垂帘"]', '帘身展开时为平整平面，几乎无立体褶皱'),
('six_dim_C', 'CW-分幅拼接', '分幅拼接', 'CW', 7, '["多幅拼帘","拼色帘身"]', '帘身由多个布幅或色块以可见缝线拼接'),
('six_dim_C', 'CW-异形/其他', '异形/其他', 'CW', 8, '["特殊褶型","其他帘身组合"]', '无法归入以上类型的帘身褶型或组合')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 D 维度 × CW 窗帘/窗饰（9 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_D', 'CW-窗帘杆', '窗帘杆', 'CW', 1, '["明杆","罗马杆"]', '帘体悬挂于可见圆杆或装饰杆'),
('six_dim_D', 'CW-壁装轨道', '壁装轨道', 'CW', 2, '["墙装滑轨","侧装轨道"]', '轨道通过支架固定在窗上方墙面'),
('six_dim_D', 'CW-顶装轨道', '顶装轨道', 'CW', 3, '["顶装滑轨","天花轨道"]', '轨道直接固定于顶面或窗洞顶部'),
('six_dim_D', 'CW-隐藏轨道', '隐藏轨道', 'CW', 4, '["暗轨","帘盒内轨道"]', '轨道藏于帘盒或吊顶槽内，正面不可见'),
('six_dim_D', 'CW-窗框内装', '窗框内装', 'CW', 5, '["内嵌安装","窗洞内装"]', '帘体与机构整体安装在窗框内侧'),
('six_dim_D', 'CW-手拉', '手拉', 'CW', 6, '["手动开合","直接拉帘"]', '直接用手拉动帘身，无可见拉珠或电机'),
('six_dim_D', 'CW-拉珠/拉绳', '拉珠/拉绳', 'CW', 7, '["珠链拉绳","循环拉珠"]', '窗侧可见珠链、拉绳或拉带操作件'),
('six_dim_D', 'CW-电动轨道', '电动轨道', 'CW', 8, '["电机帘","智能窗帘轨"]', '可见电机端头、电源线或图文明确标注电动'),
('six_dim_D', 'CW-异形/其他', '异形/其他', 'CW', 9, '["特殊安装窗饰","其他驱动"]', '无法归入以上类型的安装或驱动方式')
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- 六维 F 维度 × CW 窗帘/窗饰（11 项）
INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES
('six_dim_F', 'CW-普通遮光', '普通遮光', 'CW', 1, '["常规遮光","日常窗帘"]', '只在图文标注普通遮光或无更高等级时选择'),
('six_dim_F', 'CW-高遮光', '高遮光', 'CW', 2, '["高遮光帘","80%遮光"]', '商品图文明确标注高遮光或较高遮光率'),
('six_dim_F', 'CW-全遮光', '全遮光', 'CW', 3, '["全黑窗帘","blackout"]', '商品图文明确标注全遮光、百分百遮光或 blackout'),
('six_dim_F', 'CW-透光不透人', '透光不透人', 'CW', 4, '["隐私纱","采光纱帘"]', '帘身允许日光透过，同时图文标注保护隐私'),
('six_dim_F', 'CW-纯装饰', '纯装饰', 'CW', 5, '["装饰帘","帘楣装饰"]', '主要用于视觉装饰，无明显遮光或隐私功能'),
('six_dim_F', 'CW-隔热', '隔热', 'CW', 6, '["保温窗帘","隔热帘"]', '图文明确标注隔热、保温或反射热能'),
('six_dim_F', 'CW-吸音', '吸音', 'CW', 7, '["吸音窗帘","降噪帘"]', '图文明确标注声学吸音或降噪性能'),
('six_dim_F', 'CW-电动', '电动', 'CW', 8, '["智能开合","电机驱动"]', '可见电机或图文明确标注遥控、智能电动'),
('six_dim_F', 'CW-阻燃', '阻燃', 'CW', 9, '["防火窗帘","阻燃布"]', '只在图文或规格明确标注阻燃等级时判定'),
('six_dim_F', 'CW-可水洗', '可水洗', 'CW', 10, '["水洗窗帘","可洗帘"]', '洗涤标识或商品文字明确说明可水洗'),
('six_dim_F', 'CW-异形/其他', '异形/其他', 'CW', 11, '["其他窗饰功能","特殊功能帘"]', '只记录图片或明确商品文字可确认的其他功能')
ON CONFLICT (dict_type, dict_code) DO NOTHING;
-- <<< PRODUCT_TAXONOMY_SEED <<<
