-- 产品属性知识层：补齐旧九类元数据、补充二级产品类型，并定义属性语义与归属层。
-- 本迁移不更新任何 RSPU/Variant/RSKU 数据，也不参与现有编码、识别、报价或订单逻辑。

CREATE TABLE IF NOT EXISTS knowledge_product_attribute (
    attribute_id VARCHAR(96) PRIMARY KEY,
    attribute_code VARCHAR(64) NOT NULL,
    attribute_name VARCHAR(64) NOT NULL,
    category_dict_type VARCHAR(32) NOT NULL DEFAULT 'category',
    category_code VARCHAR(16),
    product_type_code VARCHAR(64),
    value_layer VARCHAR(16) NOT NULL,
    value_type VARCHAR(16) NOT NULL,
    unit VARCHAR(16),
    enum_options JSONB NOT NULL DEFAULT '[]'::jsonb,
    aliases JSONB NOT NULL DEFAULT '[]'::jsonb,
    description TEXT NOT NULL,
    ai_extractable BOOLEAN NOT NULL DEFAULT FALSE,
    required_level VARCHAR(16) NOT NULL DEFAULT 'optional',
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    knowledge_version VARCHAR(16) NOT NULL DEFAULT '1.0',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_attribute_product_type
        FOREIGN KEY (product_type_code) REFERENCES knowledge_product_type(type_code),
    CONSTRAINT fk_product_attribute_category
        FOREIGN KEY (category_dict_type, category_code) REFERENCES category_dict(dict_type, dict_code),
    CONSTRAINT chk_product_attribute_scope
        CHECK (category_code IS NULL OR product_type_code IS NULL),
    CONSTRAINT chk_product_attribute_layer
        CHECK (value_layer IN ('RSPU', 'VARIANT', 'RSKU')),
    CONSTRAINT chk_product_attribute_value_type
        CHECK (value_type IN ('text', 'integer', 'decimal', 'boolean', 'enum', 'multi_enum')),
    CONSTRAINT chk_product_attribute_required_level
        CHECK (required_level IN ('optional', 'recommended', 'required'))
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_product_attribute_scope_code
    ON knowledge_product_attribute (
        COALESCE(category_code, ''),
        COALESCE(product_type_code, ''),
        attribute_code
    );
CREATE INDEX IF NOT EXISTS idx_product_attribute_category
    ON knowledge_product_attribute(category_code, status, sort_order);
CREATE INDEX IF NOT EXISTS idx_product_attribute_product_type
    ON knowledge_product_attribute(product_type_code, status, sort_order);
CREATE INDEX IF NOT EXISTS idx_product_attribute_layer
    ON knowledge_product_attribute(value_layer, status);

-- >>> PRODUCT_ATTRIBUTE_KNOWLEDGE_SEED (generated by scripts/generate_product_attribute_seed.js, do not edit manually) >>>
-- 旧九类一级品类元数据：保留既有兼容别名，并补齐分类边界说明
UPDATE category_dict SET aliases = '["椅子","凳子","单椅","餐椅","靠背椅","休闲椅","扶手椅","长凳","床尾凳","脚踏","坐墩","矮凳"]', remark = '供坐卧但不具备典型多人沙发结构的座具；排除吧椅、办公职级椅和床。凳子、单人沙发等歧义词需结合座高、体量和结构复核。'
WHERE dict_type = 'category' AND dict_code = 'FS';
UPDATE category_dict SET aliases = '["沙发","沙发椅","单人沙发","多人沙发","双人沙发","三人沙发","转角沙发","组合沙发","模块沙发","沙发床","贵妃榻"]', remark = '以连续软包坐面、多人尺度或沙发式模块为主要特征；单人沙发与扶手椅边界需结合整体体量、连续底座和软包结构判定。'
WHERE dict_type = 'category' AND dict_code = 'SF';
UPDATE category_dict SET aliases = '["茶几","咖啡桌","客厅几","边几","角几","套几","子母几","沙发边桌","玄关台"]', remark = '客厅或休闲区使用的低桌和辅助桌；排除餐桌、书桌、办公桌及以收纳为主的柜类。'
WHERE dict_type = 'category' AND dict_code = 'TB';
UPDATE category_dict SET aliases = '["柜类","柜子","收纳柜","电视柜","餐边柜","床头柜","斗柜","衣柜","书柜","鞋柜","展示柜"]', remark = '以封闭或半封闭收纳、陈列为主要功能的柜体；排除只有开放工作台面的桌台类。'
WHERE dict_type = 'category' AND dict_code = 'FC';
UPDATE category_dict SET aliases = '["吧椅","吧凳","高脚椅","高脚凳","中岛凳","升降吧椅"]', remark = '明显高于普通座椅、面向吧台或厨房中岛使用的座具；需结合座高与脚踏结构区别于 FS 普通座椅。'
WHERE dict_type = 'category' AND dict_code = 'BS';
UPDATE category_dict SET aliases = '["办公家具","办公桌","办公椅","班台","班椅","工位","会议桌","培训桌","文件柜"]', remark = '具有明确办公场景、工位系统或职级语义的家具；家庭书房桌优先归入 DK，通用餐桌归入 DT。'
WHERE dict_type = 'category' AND dict_code = 'OF';
UPDATE category_dict SET aliases = '["餐桌","饭桌","圆餐桌","长餐桌","伸缩餐桌","宴会桌","吧台桌","岛台餐桌"]', remark = '以用餐高度和多人围坐为主要特征的桌台；排除茶几、书桌、办公会议桌和独立厨房岛柜。'
WHERE dict_type = 'category' AND dict_code = 'DT';
UPDATE category_dict SET aliases = '["床","床架","软包床","平台床","储物床","上下床","高架床","儿童床"]', remark = '指床架和完整床体，不包含独立床垫；独立床垫归入 MT，日间坐卧家具需结合是否具有正式睡眠承托结构判断。'
WHERE dict_type = 'category' AND dict_code = 'BD';
UPDATE category_dict SET aliases = '["灯具","灯饰","吊灯","吸顶灯","壁灯","落地灯","台灯","轨道灯","筒灯","射灯"]', remark = '具有独立照明功能及灯体、光源或安装结构的产品；排除仅发光但主要用途不是照明的装饰物。'
WHERE dict_type = 'category' AND dict_code = 'LT';

-- 补充二级产品类型：知识层旁路，不关联 RSPU，不参与编码/报价/订单/同款
INSERT INTO knowledge_product_type
    (type_code, type_name, business_category_code, schema_category_code, parent_type_code, aliases, room_tags, description, sort_order) VALUES
('DINING_BENCH', '餐凳', 'FS', 'FS', 'BENCH', '["餐桌长凳","餐厅长凳"]'::jsonb, '["DINING_ROOM"]'::jsonb, '与餐桌配套的多人长条座具', 1001),
('SHOE_BENCH', '换鞋凳', 'FS', 'FS', 'BENCH', '["玄关凳","鞋柜凳"]'::jsonb, '["ENTRYWAY"]'::jsonb, '供入户换鞋使用的凳类', 1002),
('WINDOW_BENCH', '窗边凳', 'FS', 'FS', 'BENCH', '["飘窗凳","窗台凳"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '靠窗或飘窗区域使用的长凳', 1003),
('VANITY_STOOL', '梳妆凳', 'FS', 'FS', 'STOOL', '["化妆凳","妆凳"]'::jsonb, '["BEDROOM"]'::jsonb, '与梳妆台配套的低凳', 1004),
('BATHROOM_VANITY', '浴室柜', 'FC', 'FC', NULL, '["洗手台柜","卫浴柜"]'::jsonb, '["BATHROOM"]'::jsonb, '与洗手盆组合的浴室收纳柜', 1005),
('LINEN_CABINET', '布草柜', 'FC', 'FC', NULL, '["毛巾柜","床品柜"]'::jsonb, '["BATHROOM","BEDROOM"]'::jsonb, '用于收纳毛巾、床品等布草的柜体', 1006),
('KIDS_STORAGE_CABINET', '儿童收纳柜', 'FC', 'FC', NULL, '["玩具柜","儿童柜"]'::jsonb, '["KIDS_ROOM"]'::jsonb, '适合儿童高度和安全要求的收纳柜', 1007),
('CRIB', '婴儿床', 'BD', 'BD', NULL, '["宝宝床","围栏婴儿床"]'::jsonb, '["KIDS_ROOM"]'::jsonb, '四周具有防护围栏的婴幼儿睡眠床', 1008),
('MURPHY_BED', '壁床/墨菲床', 'BD', 'BD', NULL, '["翻板床","隐藏床"]'::jsonb, '["BEDROOM","GUEST_ROOM"]'::jsonb, '可向墙柜方向翻起收纳的床', 1009),
('ADJUSTABLE_BED', '电动调节床', 'BD', 'BD', NULL, '["护理床","升降床"]'::jsonb, '["BEDROOM"]'::jsonb, '床面角度或高度可电动调节的床', 1010),
('VANITY_LIGHT', '镜前灯', 'LT', 'LT', NULL, '["浴室镜灯","化妆镜灯"]'::jsonb, '["BATHROOM","BEDROOM"]'::jsonb, '安装于镜面周边或上方的局部照明灯', 1011),
('CABINET_LIGHT', '柜内灯', 'LT', 'LT', NULL, '["橱柜灯","层板灯"]'::jsonb, '["KITCHEN","CLOAKROOM"]'::jsonb, '安装于柜内或层板下方的辅助灯具', 1012),
('OUTDOOR_LIGHT', '户外灯', 'LT', 'LT', NULL, '["户外壁灯","防水灯"]'::jsonb, '["OUTDOOR","BALCONY"]'::jsonb, '具备户外耐候用途的照明灯具', 1013),
('GARDEN_LIGHT', '庭院灯', 'LT', 'LT', NULL, '["草坪灯","景观灯"]'::jsonb, '["OUTDOOR"]'::jsonb, '用于庭院、步道或草坪的景观照明', 1014),
('DRESSING_TABLE', '梳妆台', 'DK', 'DK', NULL, '["化妆台","妆台"]'::jsonb, '["BEDROOM"]'::jsonb, '以梳妆、化妆和小件收纳为主的桌台', 1015),
('DRAFTING_TABLE', '绘图桌', 'DK', 'DK', NULL, '["制图桌","画图桌"]'::jsonb, '["STUDY","STUDIO"]'::jsonb, '台面角度可调或适合绘图制图的工作桌', 1016),
('GAMING_DESK', '游戏桌', 'DK', 'DK', NULL, '["电竞桌","电竞电脑桌"]'::jsonb, '["STUDY","BEDROOM"]'::jsonb, '面向电脑游戏设备、走线和外设布置的桌台', 1017),
('KIDS_STUDY_DESK', '儿童学习桌', 'DK', 'DK', NULL, '["学生桌","成长书桌"]'::jsonb, '["KIDS_ROOM","STUDY"]'::jsonb, '适合儿童身高并常带高度调节的学习桌', 1018),
('MATTRESS_TOPPER', '床垫薄垫/保护层', 'MT', 'MT', NULL, '["床褥","床垫加垫"]'::jsonb, '["BEDROOM"]'::jsonb, '铺设于主床垫上方的较薄舒适层', 1019),
('AIR_MATTRESS', '充气床垫', 'MT', 'MT', NULL, '["气垫床","充气床"]'::jsonb, '["GUEST_ROOM","OUTDOOR"]'::jsonb, '通过充气形成承托结构的便携床垫', 1020),
('KIDS_MATTRESS', '儿童床垫', 'MT', 'MT', NULL, '["婴儿床垫","青少年床垫"]'::jsonb, '["KIDS_ROOM"]'::jsonb, '适配婴童或儿童床规格的床垫', 1021),
('TABLE_MIRROR', '台镜', 'MR', 'MR', NULL, '["桌面镜","折叠台镜"]'::jsonb, '["BEDROOM","BATHROOM"]'::jsonb, '依靠底座放置于桌面的可移动镜子', 1022),
('LIGHTED_MIRROR', '灯光镜', 'MR', 'MR', NULL, '["发光镜","LED镜"]'::jsonb, '["BATHROOM","BEDROOM"]'::jsonb, '镜面或边框集成照明的镜子', 1023),
('IRREGULAR_RUG', '异形地毯', 'RG', 'RG', 'AREA_RUG', '["不规则地毯","造型毯"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '外轮廓为自由曲线或非规则几何形的区域毯', 1024),
('CARPET_TILE', '拼块地毯', 'RG', 'RG', NULL, '["方块地毯","地毯砖"]'::jsonb, '["OFFICE","COMMERCIAL"]'::jsonb, '由标准化小块拼铺的地毯系统', 1025),
('WALL_TO_WALL_CARPET', '满铺地毯', 'RG', 'RG', NULL, '["工程地毯","整屋地毯"]'::jsonb, '["BEDROOM","OFFICE"]'::jsonb, '按房间边界连续铺设的地毯', 1026),
('HIDE_RUG', '皮毛毯', 'RG', 'RG', NULL, '["牛皮毯","羊皮毯"]'::jsonb, '["LIVING_ROOM","BEDROOM"]'::jsonb, '保留动物皮张或仿皮毛自然轮廓的地毯', 1027),
('HANGING_DIVIDER', '悬挂隔断', 'PD', 'PD', NULL, '["吊挂隔断","吊屏"]'::jsonb, '["LIVING_ROOM","COMMERCIAL"]'::jsonb, '由顶部吊挂、底部不落地的空间隔断', 1028),
('GRILLE_PARTITION', '格栅隔断', 'PD', 'PD', NULL, '["木格栅","竖条隔断"]'::jsonb, '["LIVING_ROOM","ENTRYWAY"]'::jsonb, '由重复条杆构成的半通透隔断', 1029),
('FIXED_SCREEN', '固定屏风', 'PD', 'PD', NULL, '["固定隔断","落地固定屏"]'::jsonb, '["LIVING_ROOM","OFFICE"]'::jsonb, '固定于地面、墙面或顶面的非活动屏风', 1030),
('VERTICAL_BLIND', '垂直帘', 'CW', 'CW', NULL, '["竖百叶","垂直百叶"]'::jsonb, '["OFFICE","LIVING_ROOM"]'::jsonb, '由多片竖向叶片并排悬挂的窗饰', 1031),
('ZEBRA_BLIND', '斑马帘/柔纱帘', 'CW', 'CW', NULL, '["柔纱帘","调光帘"]'::jsonb, '["LIVING_ROOM","STUDY"]'::jsonb, '透纱和遮光条带交替错位调光的卷帘', 1032),
('BAMBOO_BLIND', '竹帘', 'CW', 'CW', NULL, '["竹卷帘","木织帘"]'::jsonb, '["STUDY","BALCONY"]'::jsonb, '以竹木条片或天然纤维编织的窗饰', 1033)
ON CONFLICT (type_code) DO UPDATE SET
    type_name = EXCLUDED.type_name,
    business_category_code = EXCLUDED.business_category_code,
    schema_category_code = EXCLUDED.schema_category_code,
    parent_type_code = EXCLUDED.parent_type_code,
    aliases = EXCLUDED.aliases,
    room_tags = EXCLUDED.room_tags,
    description = EXCLUDED.description,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;

-- 产品属性定义：只定义语义与归属层，不自动回写任何现有产品数据
INSERT INTO knowledge_product_attribute
    (attribute_id, attribute_code, attribute_name, category_code, product_type_code, value_layer, value_type, unit, enum_options, aliases, description, ai_extractable, required_level, sort_order) VALUES
('ATTR-GENERIC-INDOOR_OUTDOOR', 'INDOOR_OUTDOOR', '使用环境', NULL, NULL, 'RSPU', 'enum', NULL, '[{"code":"INDOOR","name":"室内"},{"code":"OUTDOOR","name":"户外"},{"code":"BOTH","name":"室内外通用"}]'::jsonb, '["室内外","户外适用","使用环境"]'::jsonb, '产品设计适用的环境范围，不以单张场景图推断', true, 'recommended', 1),
('ATTR-GENERIC-TARGET_USERS', 'TARGET_USERS', '适用人群', NULL, NULL, 'RSPU', 'multi_enum', NULL, '[{"code":"ADULT","name":"成人"},{"code":"KIDS","name":"儿童"},{"code":"ELDERLY","name":"适老"},{"code":"ACCESSIBLE","name":"无障碍"}]'::jsonb, '["适用对象","人群"]'::jsonb, '产品设计明确面向的人群，可多选', false, 'optional', 2),
('ATTR-GENERIC-INSTALL_METHOD', 'INSTALL_METHOD', '安装方式', NULL, NULL, 'RSPU', 'multi_enum', NULL, '[{"code":"FLOOR","name":"落地"},{"code":"WALL","name":"壁挂"},{"code":"CEILING","name":"吊装"},{"code":"RECESSED","name":"嵌入"},{"code":"HANGING","name":"悬挂"}]'::jsonb, '["固定方式","安装类型"]'::jsonb, '产品设计要求的主要安装或放置方式', true, 'recommended', 3),
('ATTR-GENERIC-MODULARITY', 'MODULARITY', '组合方式', NULL, NULL, 'RSPU', 'enum', NULL, '[{"code":"FIXED","name":"固定单体"},{"code":"MODULAR","name":"模块化"},{"code":"SET","name":"成套组合"}]'::jsonb, '["模块化","组合形式"]'::jsonb, '款式是固定单体、可重组模块还是成套销售组合', true, 'optional', 4),
('ATTR-GENERIC-FUNCTION_TAGS', 'FUNCTION_TAGS', '功能标签', NULL, NULL, 'RSPU', 'multi_enum', NULL, '[{"code":"STORAGE","name":"储物"},{"code":"FOLDING","name":"折叠"},{"code":"EXTENDABLE","name":"伸缩"},{"code":"HEIGHT_ADJUSTABLE","name":"升降"},{"code":"SWIVEL","name":"旋转"},{"code":"RECLINING","name":"躺倒"},{"code":"MOBILE","name":"移动"}]'::jsonb, '["功能","特性"]'::jsonb, '跨品类的稳定功能集合，只有图片或文字明确时记录', true, 'optional', 5),
('ATTR-GENERIC-CARE_METHOD', 'CARE_METHOD', '清洁维护方式', NULL, NULL, 'RSPU', 'multi_enum', NULL, '[{"code":"WIPE_CLEAN","name":"擦拭清洁"},{"code":"DRY_CLEAN","name":"干洗"},{"code":"HAND_WASH","name":"手洗"},{"code":"MACHINE_WASH","name":"机洗"},{"code":"PROFESSIONAL","name":"专业维护"}]'::jsonb, '["洗护","保养方式"]'::jsonb, '商品说明明确给出的清洁维护要求', false, 'optional', 6),
('ATTR-GENERIC-ASSEMBLY_MODE', 'ASSEMBLY_MODE', '交付组装方式', NULL, NULL, 'RSKU', 'enum', NULL, '[{"code":"ASSEMBLED","name":"整装"},{"code":"PARTIAL","name":"部分组装"},{"code":"KNOCK_DOWN","name":"拆装包装"},{"code":"PROFESSIONAL","name":"专业安装"}]'::jsonb, '["安装服务","组装要求"]'::jsonb, '具体供应单元的包装交付和安装要求', false, 'optional', 7),
('ATTR-GENERIC-CERTIFICATION_TAGS', 'CERTIFICATION_TAGS', '认证标签', NULL, NULL, 'RSKU', 'multi_enum', NULL, '[{"code":"FSC","name":"FSC"},{"code":"BSCI","name":"BSCI"},{"code":"GREENGUARD","name":"GREENGUARD"},{"code":"CE","name":"CE"},{"code":"ROHS","name":"RoHS"},{"code":"OTHER","name":"其他"}]'::jsonb, '["资质","认证"]'::jsonb, '工厂或具体供应单元可提供证明材料的认证', false, 'optional', 8),
('ATTR-FS-SEAT_COUNT', 'SEAT_COUNT', '座位数', 'FS', NULL, 'RSPU', 'integer', 'seat', '[]'::jsonb, '["几人位","座数"]'::jsonb, '正常坐姿下的设计座位数量', true, 'recommended', 1),
('ATTR-FS-SEAT_HEIGHT_MM', 'SEAT_HEIGHT_MM', '座高', 'FS', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["坐高","座面高"]'::jsonb, '地面至主要座面的垂直高度', false, 'recommended', 2),
('ATTR-FS-MAX_LOAD_KG', 'MAX_LOAD_KG', '最大承重', 'FS', NULL, 'VARIANT', 'decimal', 'kg', '[]'::jsonb, '["承重","载重"]'::jsonb, '有测试或规格依据的最大静态承重', false, 'optional', 3),
('ATTR-FS-STACKABLE', 'STACKABLE', '可堆叠', 'FS', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["叠放","可摞放"]'::jsonb, '椅凳是否设计为可稳定堆叠收纳', true, 'optional', 4),
('ATTR-FS-SWIVEL', 'SWIVEL', '可旋转', 'FS', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["转椅","旋转底座"]'::jsonb, '座面或底座是否具备旋转机构', true, 'optional', 5),
('ATTR-FS-RECLINING', 'RECLINING', '可躺调节', 'FS', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["躺倒","靠背调节"]'::jsonb, '靠背或脚托是否具备躺倒调节功能', true, 'optional', 6),
('ATTR-SF-SEAT_COUNT', 'SEAT_COUNT', '座位数', 'SF', NULL, 'RSPU', 'integer', 'seat', '[]'::jsonb, '["几人位","座数"]'::jsonb, '沙发正常坐姿下的设计座位数量', true, 'recommended', 1),
('ATTR-SF-SEAT_HEIGHT_MM', 'SEAT_HEIGHT_MM', '座高', 'SF', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["坐高","座面高"]'::jsonb, '地面至主要座面的垂直高度', false, 'optional', 2),
('ATTR-SF-SECTION_COUNT', 'SECTION_COUNT', '模块/分段数', 'SF', NULL, 'VARIANT', 'integer', 'piece', '[]'::jsonb, '["模块数","组合件数"]'::jsonb, '当前组合变体包含的独立沙发模块或分段数量', true, 'optional', 3),
('ATTR-SF-RECLINING', 'RECLINING', '功能躺位', 'SF', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["电动躺位","脚托"]'::jsonb, '是否具有可展开脚托或靠背躺倒机构', true, 'optional', 4),
('ATTR-TB-TABLETOP_HEIGHT_MM', 'TABLETOP_HEIGHT_MM', '台面高度', 'TB', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["几高","桌面高"]'::jsonb, '地面至主要台面的高度', false, 'recommended', 1),
('ATTR-TB-NESTING_COUNT', 'NESTING_COUNT', '套几件数', 'TB', NULL, 'VARIANT', 'integer', 'piece', '[]'::jsonb, '["组合数量","几件套"]'::jsonb, '套几或组合几包含的单体数量', true, 'optional', 2),
('ATTR-TB-MOBILE', 'MOBILE', '可移动', 'TB', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["带轮","移动茶几"]'::jsonb, '是否设计有脚轮或专用移动结构', true, 'optional', 3),
('ATTR-FC-DOOR_COUNT', 'DOOR_COUNT', '门扇数', 'FC', NULL, 'VARIANT', 'integer', 'piece', '[]'::jsonb, '["柜门数","门数"]'::jsonb, '当前变体可开启的柜门数量', true, 'optional', 1),
('ATTR-FC-DRAWER_COUNT', 'DRAWER_COUNT', '抽屉数', 'FC', NULL, 'VARIANT', 'integer', 'piece', '[]'::jsonb, '["斗数","抽数"]'::jsonb, '当前变体独立抽屉数量', true, 'optional', 2),
('ATTR-FC-SHELF_COUNT', 'SHELF_COUNT', '层板数', 'FC', NULL, 'VARIANT', 'integer', 'piece', '[]'::jsonb, '["隔板数","层数"]'::jsonb, '当前变体可用层板数量', false, 'optional', 3),
('ATTR-FC-MOUNTING_TYPE', 'MOUNTING_TYPE', '柜体安装类型', 'FC', NULL, 'RSPU', 'enum', NULL, '[{"code":"FREESTANDING","name":"独立落地"},{"code":"WALL_MOUNTED","name":"壁挂"},{"code":"BUILT_IN","name":"嵌入/固定"}]'::jsonb, '["柜体固定方式","落地壁挂"]'::jsonb, '柜体主要安装方式', true, 'recommended', 4),
('ATTR-FC-TV_SIZE_INCH', 'TV_SIZE_INCH', '适配电视尺寸', 'FC', NULL, 'VARIANT', 'decimal', 'inch', '[]'::jsonb, '["电视英寸","适配屏幕"]'::jsonb, '电视柜明确标注可适配的最大电视尺寸', false, 'optional', 5),
('ATTR-BS-SEAT_HEIGHT_MM', 'SEAT_HEIGHT_MM', '座高', 'BS', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["吧椅高度","坐高"]'::jsonb, '地面至座面的垂直高度，是区分吧椅与普通座椅的关键值', false, 'required', 1),
('ATTR-BS-HEIGHT_ADJUSTABLE', 'HEIGHT_ADJUSTABLE', '高度可调', 'BS', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["升降","可调高"]'::jsonb, '座面高度是否可调', true, 'optional', 2),
('ATTR-BS-HAS_FOOTREST', 'HAS_FOOTREST', '带脚踏', 'BS', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["脚踏环","搁脚"]'::jsonb, '是否具有脚踏环或横向搁脚杆', true, 'optional', 3),
('ATTR-BS-SWIVEL', 'SWIVEL', '可旋转', 'BS', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["旋转吧椅","转动"]'::jsonb, '座面是否可围绕中柱旋转', true, 'optional', 4),
('ATTR-BS-MAX_LOAD_KG', 'MAX_LOAD_KG', '最大承重', 'BS', NULL, 'VARIANT', 'decimal', 'kg', '[]'::jsonb, '["承重","载重"]'::jsonb, '有测试或规格依据的最大静态承重', false, 'optional', 5),
('ATTR-OF-COMMERCIAL_GRADE', 'COMMERCIAL_GRADE', '商用强度等级', 'OF', NULL, 'RSKU', 'enum', NULL, '[{"code":"HOME","name":"家用"},{"code":"LIGHT_COMMERCIAL","name":"轻商用"},{"code":"COMMERCIAL","name":"商用"},{"code":"CONTRACT","name":"工程级"}]'::jsonb, '["结构等级","商用等级"]'::jsonb, '具体供应单元可验证的使用强度等级', false, 'optional', 1),
('ATTR-OF-CABLE_MANAGEMENT', 'CABLE_MANAGEMENT', '走线管理', 'OF', NULL, 'RSPU', 'multi_enum', NULL, '[{"code":"GROMMET","name":"过线孔"},{"code":"CABLE_TRAY","name":"走线槽"},{"code":"CABLE_BOX","name":"线盒"},{"code":"VERTICAL_CHANNEL","name":"竖向走线"}]'::jsonb, '["线孔","走线槽"]'::jsonb, '桌台可见或规格明确的线缆管理结构', true, 'optional', 2),
('ATTR-OF-HEIGHT_ADJUSTABLE', 'HEIGHT_ADJUSTABLE', '高度可调', 'OF', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["升降办公桌","升降椅"]'::jsonb, '桌面或座面高度是否可调，需结合 product_type 理解', true, 'optional', 3),
('ATTR-OF-WORKSTATION_CAPACITY', 'WORKSTATION_CAPACITY', '工位人数', 'OF', NULL, 'VARIANT', 'integer', 'seat', '[]'::jsonb, '["几人位工位","工位数"]'::jsonb, '工位系统当前组合可容纳的人数', false, 'optional', 4),
('ATTR-DT-TABLETOP_HEIGHT_MM', 'TABLETOP_HEIGHT_MM', '台面高度', 'DT', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["餐桌高","桌面高"]'::jsonb, '地面至主要用餐台面的高度', false, 'recommended', 1),
('ATTR-DT-SEATING_CAPACITY', 'SEATING_CAPACITY', '建议用餐人数', 'DT', NULL, 'VARIANT', 'integer', 'seat', '[]'::jsonb, '["几人桌","容纳人数"]'::jsonb, '当前尺寸变体建议同时用餐的人数', false, 'recommended', 2),
('ATTR-DT-EXTENDABLE', 'EXTENDABLE', '可伸缩', 'DT', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["延长桌","拉伸桌"]'::jsonb, '台面是否可通过拉伸、翻板等方式扩展', true, 'optional', 3),
('ATTR-BD-MATTRESS_SIZE', 'MATTRESS_SIZE', '适配床垫规格', 'BD', NULL, 'VARIANT', 'text', NULL, '[]'::jsonb, '["床垫尺寸","床规格"]'::jsonb, '床架适配的标准或原始床垫尺寸表达', false, 'required', 1),
('ATTR-BD-SLEEPING_CAPACITY', 'SLEEPING_CAPACITY', '睡眠人数', 'BD', NULL, 'VARIANT', 'integer', 'person', '[]'::jsonb, '["单人双人","容纳人数"]'::jsonb, '当前尺寸变体设计容纳的睡眠人数', false, 'optional', 2),
('ATTR-BD-UNDERBED_STORAGE', 'UNDERBED_STORAGE', '床下储物', 'BD', NULL, 'RSPU', 'enum', NULL, '[{"code":"NONE","name":"无"},{"code":"DRAWER","name":"抽屉储物"},{"code":"LIFT_UP","name":"掀床储物"},{"code":"OPEN","name":"开放置物"}]'::jsonb, '["高箱床","床下抽屉"]'::jsonb, '床下储物的主要结构形式', true, 'optional', 3),
('ATTR-BD-HEADBOARD_HEIGHT_MM', 'HEADBOARD_HEIGHT_MM', '床头高度', 'BD', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["靠背高","床屏高度"]'::jsonb, '地面至床头最高点的垂直高度', false, 'optional', 4),
('ATTR-LT-LIGHT_SOURCE', 'LIGHT_SOURCE', '光源类型', 'LT', NULL, 'VARIANT', 'enum', NULL, '[{"code":"INTEGRATED_LED","name":"集成 LED"},{"code":"REPLACEABLE_BULB","name":"可更换灯泡"},{"code":"LIGHT_STRIP","name":"灯带"},{"code":"OTHER","name":"其他"}]'::jsonb, '["灯芯","光源"]'::jsonb, '当前灯具变体使用的主要光源形式', false, 'recommended', 1),
('ATTR-LT-BULB_BASE', 'BULB_BASE', '灯头接口', 'LT', NULL, 'VARIANT', 'text', NULL, '[]'::jsonb, '["灯口","灯座"]'::jsonb, '如 E27、E14、GU10 等标准灯头接口', false, 'optional', 2),
('ATTR-LT-POWER_W', 'POWER_W', '功率', 'LT', NULL, 'VARIANT', 'decimal', 'W', '[]'::jsonb, '["瓦数","额定功率"]'::jsonb, '当前灯具变体的额定功率', false, 'optional', 3),
('ATTR-LT-COLOR_TEMPERATURE_K', 'COLOR_TEMPERATURE_K', '色温', 'LT', NULL, 'VARIANT', 'integer', 'K', '[]'::jsonb, '["光色","开尔文"]'::jsonb, '当前灯具变体标注的色温', false, 'optional', 4),
('ATTR-LT-DIMMABLE', 'DIMMABLE', '可调光', 'LT', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["调光","亮度调节"]'::jsonb, '是否支持亮度调节', false, 'optional', 5),
('ATTR-LT-VOLTAGE_V', 'VOLTAGE_V', '额定电压', 'LT', NULL, 'VARIANT', 'text', 'V', '[]'::jsonb, '["电压","输入电压"]'::jsonb, '当前灯具变体适用的电压范围', false, 'optional', 6),
('ATTR-LT-IP_RATING', 'IP_RATING', '防护等级', 'LT', NULL, 'RSKU', 'text', NULL, '[]'::jsonb, '["防水等级","IP等级"]'::jsonb, '具体供应单元具备检测或规格依据的 IP 防护等级', false, 'optional', 7),
('ATTR-DK-TABLETOP_HEIGHT_MM', 'TABLETOP_HEIGHT_MM', '台面高度', 'DK', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["桌面高","书桌高"]'::jsonb, '地面至主要工作台面的高度', false, 'recommended', 1),
('ATTR-DK-CABLE_MANAGEMENT', 'CABLE_MANAGEMENT', '走线管理', 'DK', NULL, 'RSPU', 'multi_enum', NULL, '[{"code":"GROMMET","name":"过线孔"},{"code":"CABLE_TRAY","name":"走线槽"},{"code":"CABLE_BOX","name":"线盒"},{"code":"VERTICAL_CHANNEL","name":"竖向走线"}]'::jsonb, '["线孔","走线槽"]'::jsonb, '可见或规格明确的线缆管理结构', true, 'optional', 2),
('ATTR-DK-HEIGHT_ADJUSTABLE', 'HEIGHT_ADJUSTABLE', '高度可调', 'DK', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["成长桌","升降桌"]'::jsonb, '工作台面高度是否可调', true, 'optional', 3),
('ATTR-DK-TILT_ADJUSTABLE', 'TILT_ADJUSTABLE', '台面角度可调', 'DK', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["斜面调节","绘图桌角度"]'::jsonb, '台面是否可改变倾斜角度', true, 'optional', 4),
('ATTR-MT-THICKNESS_MM', 'THICKNESS_MM', '床垫厚度', 'MT', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["垫厚","总厚度"]'::jsonb, '床垫当前变体的整体厚度', false, 'required', 1),
('ATTR-MT-FIRMNESS', 'FIRMNESS', '软硬度', 'MT', NULL, 'VARIANT', 'enum', NULL, '[{"code":"SOFT","name":"偏软"},{"code":"MEDIUM_SOFT","name":"中软"},{"code":"MEDIUM","name":"适中"},{"code":"MEDIUM_FIRM","name":"中硬"},{"code":"FIRM","name":"偏硬"}]'::jsonb, '["硬度","睡感"]'::jsonb, '以工厂或品牌规格为依据的软硬度，不从外观猜测', false, 'recommended', 2),
('ATTR-MT-CORE_STRUCTURE', 'CORE_STRUCTURE', '内芯结构', 'MT', NULL, 'VARIANT', 'multi_enum', NULL, '[{"code":"SPRING","name":"弹簧"},{"code":"FOAM","name":"泡棉"},{"code":"LATEX","name":"乳胶"},{"code":"COIR","name":"椰棕"},{"code":"AIR","name":"充气"}]'::jsonb, '["内材","承托层"]'::jsonb, '仅依据剖面图或明确文字记录的内部承托结构', false, 'optional', 3),
('ATTR-MT-REVERSIBLE', 'REVERSIBLE', '双面可用', 'MT', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["双面睡感","正反两用"]'::jsonb, '床垫是否明确支持翻面使用', false, 'optional', 4),
('ATTR-MT-REMOVABLE_COVER', 'REMOVABLE_COVER', '外套可拆洗', 'MT', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["可拆套","拉链外套"]'::jsonb, '外层套是否可拆卸清洗', true, 'optional', 5),
('ATTR-MR-MOUNTING_TYPE', 'MOUNTING_TYPE', '镜子安装方式', 'MR', NULL, 'RSPU', 'enum', NULL, '[{"code":"WALL","name":"壁挂"},{"code":"FLOOR","name":"落地"},{"code":"TABLE","name":"台面"},{"code":"RECESSED","name":"嵌入"}]'::jsonb, '["支撑方式","挂装方式"]'::jsonb, '镜子的主要安装或支撑方式', true, 'recommended', 1),
('ATTR-MR-LIGHTING', 'LIGHTING', '集成灯光', 'MR', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["LED镜","发光镜"]'::jsonb, '镜体是否集成照明', true, 'optional', 2),
('ATTR-MR-ANTI_FOG', 'ANTI_FOG', '防雾', 'MR', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["除雾","电加热防雾"]'::jsonb, '是否具有明确的防雾或除雾功能', false, 'optional', 3),
('ATTR-MR-MAGNIFICATION', 'MAGNIFICATION', '放大倍率', 'MR', NULL, 'VARIANT', 'decimal', 'x', '[]'::jsonb, '["放大镜倍率","倍数"]'::jsonb, '化妆镜等产品明确标注的放大倍率', false, 'optional', 4),
('ATTR-RG-PILE_HEIGHT_MM', 'PILE_HEIGHT_MM', '绒高', 'RG', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["毛高","绒毛高度"]'::jsonb, '地毯表面绒毛的标称高度', false, 'optional', 1),
('ATTR-RG-WEAVE_METHOD', 'WEAVE_METHOD', '织造方式', 'RG', NULL, 'RSPU', 'enum', NULL, '[{"code":"HAND_KNOTTED","name":"手工打结"},{"code":"HAND_TUFTED","name":"手工簇绒"},{"code":"MACHINE_WOVEN","name":"机织"},{"code":"FLAT_WOVEN","name":"平织"},{"code":"BRAIDED","name":"编织"}]'::jsonb, '["工艺","织法"]'::jsonb, '仅依据工艺图或明确文字记录的织造方式', false, 'optional', 2),
('ATTR-RG-BACKING_TYPE', 'BACKING_TYPE', '背衬类型', 'RG', NULL, 'VARIANT', 'text', NULL, '[]'::jsonb, '["毯底","背胶"]'::jsonb, '地毯背面的基布、防滑层或背胶描述', false, 'optional', 3),
('ATTR-RG-MACHINE_WASHABLE', 'MACHINE_WASHABLE', '可机洗', 'RG', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["洗衣机可洗","机洗毯"]'::jsonb, '商品说明是否明确允许机洗', false, 'optional', 4),
('ATTR-RG-AREA_SQM', 'AREA_SQM', '面积', 'RG', NULL, 'VARIANT', 'decimal', 'sqm', '[]'::jsonb, '["平方米","覆盖面积"]'::jsonb, '当前地毯变体的标称覆盖面积', false, 'optional', 5),
('ATTR-RG-CUSTOM_SIZE', 'CUSTOM_SIZE', '支持定制尺寸', 'RG', NULL, 'RSKU', 'boolean', NULL, '[]'::jsonb, '["尺寸定制","可裁切"]'::jsonb, '具体工厂供应是否接受非标准尺寸定制', false, 'optional', 6),
('ATTR-PD-PANEL_COUNT', 'PANEL_COUNT', '面板数量', 'PD', NULL, 'VARIANT', 'integer', 'piece', '[]'::jsonb, '["几联","片数"]'::jsonb, '当前隔断变体包含的独立面板数量', true, 'optional', 1),
('ATTR-PD-FOLDABLE', 'FOLDABLE', '可折叠', 'PD', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["折屏","收折"]'::jsonb, '面板是否通过铰接结构折叠收拢', true, 'optional', 2),
('ATTR-PD-MOBILE', 'MOBILE', '可移动', 'PD', NULL, 'RSPU', 'boolean', NULL, '[]'::jsonb, '["带轮隔断","移动屏风"]'::jsonb, '是否设计有脚轮或其他移动结构', true, 'optional', 3),
('ATTR-PD-ACOUSTIC_RATING', 'ACOUSTIC_RATING', '声学指标', 'PD', NULL, 'RSKU', 'text', NULL, '[]'::jsonb, '["吸音系数","降噪等级"]'::jsonb, '具体供应单元有检测或规格依据的声学性能指标', false, 'optional', 4),
('ATTR-CW-FINISHED_WIDTH_MM', 'FINISHED_WIDTH_MM', '成品宽度', 'CW', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["帘宽","成品宽"]'::jsonb, '当前窗饰成品展开后的标称宽度', false, 'required', 1),
('ATTR-CW-FINISHED_DROP_MM', 'FINISHED_DROP_MM', '成品高度/帘长', 'CW', NULL, 'VARIANT', 'decimal', 'mm', '[]'::jsonb, '["帘高","帘长","下垂高度"]'::jsonb, '当前窗饰成品的标称垂直尺寸', false, 'required', 2),
('ATTR-CW-OPENING_MODE', 'OPENING_MODE', '开合方式', 'CW', NULL, 'RSPU', 'enum', NULL, '[{"code":"LEFT_RIGHT","name":"左右开合"},{"code":"UP_DOWN","name":"上下收放"},{"code":"ROTATE","name":"叶片旋转"},{"code":"FIXED","name":"固定"}]'::jsonb, '["开启方式","收帘方式"]'::jsonb, '窗饰主体的主要开合运动方式', true, 'optional', 3),
('ATTR-CW-BLACKOUT_LEVEL', 'BLACKOUT_LEVEL', '遮光等级', 'CW', NULL, 'VARIANT', 'enum', NULL, '[{"code":"SHEER","name":"透光"},{"code":"LIGHT_FILTERING","name":"半遮光"},{"code":"HIGH_BLACKOUT","name":"高遮光"},{"code":"BLACKOUT","name":"全遮光"}]'::jsonb, '["遮光率","透光性"]'::jsonb, '以检测或商品明确说明为依据的遮光等级', false, 'recommended', 4),
('ATTR-CW-MOTOR_CONTROL', 'MOTOR_CONTROL', '电机控制方式', 'CW', NULL, 'RSKU', 'multi_enum', NULL, '[{"code":"REMOTE","name":"遥控器"},{"code":"APP","name":"App"},{"code":"VOICE","name":"语音"},{"code":"WALL_SWITCH","name":"墙面开关"},{"code":"SMART_HOME","name":"智能家居接入"}]'::jsonb, '["智能控制","电动窗帘控制"]'::jsonb, '具体供应单元支持的电机控制与智能接入方式', false, 'optional', 5)
ON CONFLICT (attribute_id) DO UPDATE SET
    attribute_code = EXCLUDED.attribute_code,
    attribute_name = EXCLUDED.attribute_name,
    category_code = EXCLUDED.category_code,
    product_type_code = EXCLUDED.product_type_code,
    value_layer = EXCLUDED.value_layer,
    value_type = EXCLUDED.value_type,
    unit = EXCLUDED.unit,
    enum_options = EXCLUDED.enum_options,
    aliases = EXCLUDED.aliases,
    description = EXCLUDED.description,
    ai_extractable = EXCLUDED.ai_extractable,
    required_level = EXCLUDED.required_level,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;
-- <<< PRODUCT_ATTRIBUTE_KNOWLEDGE_SEED <<<
