#!/usr/bin/env node
// 生成旧九类元数据、补充 product_type 与产品属性定义种子。
// 用法：node scripts/generate_product_attribute_seed.js；CI 校验：追加 --check。

const fs = require('fs');
const path = require('path');
const { PRODUCT_TYPES } = require('./six_dim_extended_data');
const {
  LEGACY_CATEGORY_METADATA,
  SUPPLEMENTAL_PRODUCT_TYPES,
  PRODUCT_ATTRIBUTES,
} = require('./product_attribute_data');

const ROOT = path.resolve(__dirname, '..');
const OUTPUT_FILES = [
  path.join(ROOT, 'database', 'schema', 'zz_seed.sql'),
  path.join(ROOT, 'database', 'ops', 'reset_db.sql'),
  path.join(ROOT, 'server', 'src', 'main', 'resources', 'db', 'migration',
    'V16__product_attribute_knowledge.sql'),
];
const MARK_BEGIN = '-- >>> PRODUCT_ATTRIBUTE_KNOWLEDGE_SEED (generated by scripts/generate_product_attribute_seed.js, do not edit manually) >>>';
const MARK_END = '-- <<< PRODUCT_ATTRIBUTE_KNOWLEDGE_SEED <<<';

function sqlStr(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function jsonSql(value) {
  return `${sqlStr(JSON.stringify(value))}::jsonb`;
}

function buildSeedBlock() {
  const lines = [];
  lines.push('-- 旧九类一级品类元数据：保留既有兼容别名，并补齐分类边界说明');
  for (const category of LEGACY_CATEGORY_METADATA) {
    lines.push(`UPDATE category_dict SET aliases = ${sqlStr(JSON.stringify(category.aliases))}, remark = ${sqlStr(category.remark)}`);
    lines.push(`WHERE dict_type = 'category' AND dict_code = ${sqlStr(category.code)};`);
  }
  lines.push('');

  lines.push('-- 补充二级产品类型：知识层旁路，不关联 RSPU，不参与编码/报价/订单/同款');
  lines.push('INSERT INTO knowledge_product_type');
  lines.push('    (type_code, type_name, business_category_code, schema_category_code, parent_type_code, aliases, room_tags, description, sort_order) VALUES');
  lines.push(SUPPLEMENTAL_PRODUCT_TYPES.map((type, index) =>
    `(${sqlStr(type.typeCode)}, ${sqlStr(type.typeName)}, ${sqlStr(type.businessCategoryCode)}, ${sqlStr(type.schemaCategoryCode)}, ${sqlStr(type.parentTypeCode)}, ${jsonSql(type.aliases)}, ${jsonSql(type.roomTags)}, ${sqlStr(type.description)}, ${1000 + index + 1})`
  ).join(',\n'));
  lines.push(`ON CONFLICT (type_code) DO UPDATE SET
    type_name = EXCLUDED.type_name,
    business_category_code = EXCLUDED.business_category_code,
    schema_category_code = EXCLUDED.schema_category_code,
    parent_type_code = EXCLUDED.parent_type_code,
    aliases = EXCLUDED.aliases,
    room_tags = EXCLUDED.room_tags,
    description = EXCLUDED.description,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;`);
  lines.push('');

  lines.push('-- 产品属性定义：只定义语义与归属层，不自动回写任何现有产品数据');
  lines.push('INSERT INTO knowledge_product_attribute');
  lines.push('    (attribute_id, attribute_code, attribute_name, category_code, product_type_code, value_layer, value_type, unit, enum_options, aliases, description, ai_extractable, required_level, sort_order) VALUES');
  const scopeOrder = new Map();
  lines.push(PRODUCT_ATTRIBUTES.map((item) => {
    const scope = item.categoryCode || item.productTypeCode || 'GENERIC';
    const sortOrder = (scopeOrder.get(scope) || 0) + 1;
    scopeOrder.set(scope, sortOrder);
    return `(${sqlStr(item.attributeId)}, ${sqlStr(item.attributeCode)}, ${sqlStr(item.attributeName)}, ${sqlStr(item.categoryCode)}, ${sqlStr(item.productTypeCode)}, ${sqlStr(item.valueLayer)}, ${sqlStr(item.valueType)}, ${sqlStr(item.unit)}, ${jsonSql(item.enumOptions)}, ${jsonSql(item.aliases)}, ${sqlStr(item.description)}, ${item.aiExtractable}, ${sqlStr(item.requiredLevel)}, ${sortOrder})`;
  }).join(',\n'));
  lines.push(`ON CONFLICT (attribute_id) DO UPDATE SET
    attribute_code = EXCLUDED.attribute_code,
    attribute_name = EXCLUDED.attribute_name,
    category_code = EXCLUDED.category_code,
    product_type_code = EXCLUDED.product_type_code,
    value_layer = EXCLUDED.value_layer,
    value_type = EXCLUDED.value_type,
    unit = EXCLUDED.unit,
    enum_options = EXCLUDED.enum_options,
    aliases = EXCLUDED.aliases,
    description = EXCLUDED.description,
    ai_extractable = EXCLUDED.ai_extractable,
    required_level = EXCLUDED.required_level,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;`);
  return lines.join('\n') + '\n';
}

function replaceMarkedBlock(file, block, checkOnly) {
  const fileText = fs.readFileSync(file, 'utf8');
  const escape = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`${escape(MARK_BEGIN)}[\\s\\S]*?${escape(MARK_END)}`);
  if (!re.test(fileText)) {
    throw new Error(`标记区间未找到：${path.relative(ROOT, file)}`);
  }
  const expectedLf = `${MARK_BEGIN}\n${block}${MARK_END}`;
  const current = fileText.match(re)[0].replace(/\r\n/g, '\n');
  if (checkOnly && current !== expectedLf) {
    throw new Error(`生成内容已漂移，请运行生成器更新：${path.relative(ROOT, file)}`);
  }
  if (!checkOnly) {
    const eol = fileText.includes('\r\n') ? '\r\n' : '\n';
    const expected = eol === '\n' ? expectedLf : expectedLf.replace(/\n/g, '\r\n');
    const updated = fileText.replace(re, expected);
    if (updated !== fileText) fs.writeFileSync(file, updated, 'utf8');
  }
}

function validateData() {
  if (LEGACY_CATEGORY_METADATA.map((item) => item.code).join(',') !== 'FS,SF,TB,FC,BS,OF,DT,BD,LT') {
    throw new Error('旧九类元数据必须完整覆盖且保持既定顺序');
  }
  for (const category of LEGACY_CATEGORY_METADATA) {
    if (!category.remark || !Array.isArray(category.aliases) || category.aliases.length === 0) {
      throw new Error(`${category.code} 缺少 aliases 或分类边界说明`);
    }
  }

  const allTypeCodes = [...PRODUCT_TYPES, ...SUPPLEMENTAL_PRODUCT_TYPES].map((item) => item.typeCode);
  if (new Set(allTypeCodes).size !== allTypeCodes.length) {
    throw new Error('product_type code 存在重复');
  }
  const knownTypeCodes = new Set(allTypeCodes);
  for (const type of SUPPLEMENTAL_PRODUCT_TYPES) {
    if (!type.typeName || !type.description || type.aliases.length === 0 || type.roomTags.length === 0) {
      throw new Error(`${type.typeCode} 产品类型知识不完整`);
    }
    if (type.parentTypeCode && !knownTypeCodes.has(type.parentTypeCode)) {
      throw new Error(`${type.typeCode} 父类型不存在：${type.parentTypeCode}`);
    }
  }

  const validLayers = new Set(['RSPU', 'VARIANT', 'RSKU']);
  const validTypes = new Set(['text', 'integer', 'decimal', 'boolean', 'enum', 'multi_enum']);
  const validRequiredLevels = new Set(['optional', 'recommended', 'required']);
  const ids = new Set();
  for (const item of PRODUCT_ATTRIBUTES) {
    if (ids.has(item.attributeId)) throw new Error(`属性 ID 重复：${item.attributeId}`);
    ids.add(item.attributeId);
    if (!item.attributeCode || !item.attributeName || !item.description || item.aliases.length === 0) {
      throw new Error(`${item.attributeId} 属性定义不完整`);
    }
    if (!validLayers.has(item.valueLayer) || !validTypes.has(item.valueType)
      || !validRequiredLevels.has(item.requiredLevel)) {
      throw new Error(`${item.attributeId} 层级、值类型或必填等级非法`);
    }
    if (['enum', 'multi_enum'].includes(item.valueType) && item.enumOptions.length === 0) {
      throw new Error(`${item.attributeId} 枚举属性必须提供 enum_options`);
    }
    if (item.productTypeCode && !knownTypeCodes.has(item.productTypeCode)) {
      throw new Error(`${item.attributeId} 引用了不存在的 product_type`);
    }
  }
}

function main() {
  const checkOnly = process.argv.includes('--check');
  validateData();
  const block = buildSeedBlock();
  for (const file of OUTPUT_FILES) replaceMarkedBlock(file, block, checkOnly);
  console.log(`${checkOnly ? '已校验' : '已生成'}品类元数据 ${LEGACY_CATEGORY_METADATA.length} 类、补充 product_type ${SUPPLEMENTAL_PRODUCT_TYPES.length} 项、产品属性 ${PRODUCT_ATTRIBUTES.length} 项`);
  for (const file of OUTPUT_FILES) console.log(`  - ${path.relative(ROOT, file)}`);
}

main();
