#!/usr/bin/env node
// 六维标签字典种子生成器
// 数据源：docs/08-roadmap/六维标签体系完善方案.md 附录 A（v2.1）
// 产出：
//   1. database/V29__six_dim_dict_seed.sql（整体重写：步骤0 品类补种 + 步骤1 存量规范化 + 步骤2 全量枚举种子）
//   2. database/V1__seed_data.sql / database/reset_db.sql 中 SIX_DIM_DICT_SEED 标记区间内的种子块
// 编码规则：dict_code = {品类码}-{中文名}；dict_name = 中文名；aliases/remark 随行内联。
// E 维度（表面材质）不建独立枚举，统一引用 material/fabric 字典（方案步骤 3）。
// 用法：node scripts/generate_six_dim_dict_seed.js
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const V29_FILE = path.join(ROOT, 'database', 'V29__six_dim_dict_seed.sql');
const SEED_FILES = [
  path.join(ROOT, 'database', 'V1__seed_data.sql'),
  path.join(ROOT, 'database', 'reset_db.sql'),
];

const MARK_BEGIN = '-- >>> SIX_DIM_DICT_SEED (generated by scripts/generate_six_dim_dict_seed.js, do not edit manually) >>>';
const MARK_END = '-- <<< SIX_DIM_DICT_SEED <<<';

// 维度 key → dict_type
const DIM_TYPES = { A: 'six_dim_A', B: 'six_dim_B', C: 'six_dim_C', D: 'six_dim_D', F: 'six_dim_F' };
// 维度输出顺序
const DIM_ORDER = ['A', 'B', 'C', 'D', 'F'];

// ==================== 附录 A 枚举清单（name / aliases / remark=视觉判别要点） ====================

// A.1 FS/SF 座椅/沙发（两品类共用一套清单）
const LIST_FS_SF = {
  A: [
    { name: '一字型', aliases: ['直排', '直列'], remark: '正视呈一条直线，无转角无延伸位' },
    { name: 'L型/转角组合', aliases: ['转角沙发', '贵妃位', '贵妃榻', 'L形组合'], remark: '座位向一侧拐出或一端延伸出无靠背长躺位' },
    { name: '方盒形', aliases: ['豆腐块', '方块沙发', '盒子形'], remark: '外轮廓方正利落、棱角分明、厚度均匀的体块感' },
    { name: '弧形/环抱形', aliases: ['圆弧形', '月牙形', '腰果形', '帆船沙发'], remark: '整体呈弧线或两侧向内环抱的曲线轮廓' },
    { name: '低矮阔坐形', aliases: ['云朵沙发', '低趴沙发', '地平线沙发'], remark: '整体明显低矮、坐面宽大松软、重心贴地' },
    { name: '蛋形/球形', aliases: ['蛋椅', '蛋壳椅', '球椅', '太空舱椅'], remark: '座椅主体呈蛋/球形壳体，人被包裹在壳内' },
    { name: '贝壳/花瓣形', aliases: ['贝壳椅', '扇贝椅', '花瓣椅', '微笑椅'], remark: '座面靠背呈展开的扇形/瓣状壳体，边缘上翘' },
    { name: '分节柱形', aliases: ['毛毛虫沙发', '褶皱沙发', 'Togo式'], remark: '无外露硬骨架，由横向分节/褶皱段堆叠成低矮长条' },
    { name: '外露骨架形', aliases: ['A字架形', '骨架外露', '框架式'], remark: '木/金属骨架构成整椅主体轮廓（含靠背扶手），软包嵌挂其间' },
    { name: '沙漏形/收腰', aliases: ['收腰', '细腰'], remark: '腰线明显内收，上下两端外张' },
    { name: '模块化组合', aliases: ['模块沙发', '自由组合', '积木沙发'], remark: '可见多个独立相同模块拼接，模块间接缝清晰' },
    { name: '异形/其他', aliases: ['不规则造型', '艺术造型'], remark: '不属于以上任何一种的雕塑感/不规则轮廓' },
  ],
  B: [
    { name: '中高靠背', aliases: ['标准靠背', '中靠背'], remark: '靠背顶约在坐姿肩部附近，最常见' },
    { name: '低靠背', aliases: ['矮靠背', '半靠背'], remark: '靠背明显低于肩部，仅及腰背部' },
    { name: '高靠背', aliases: ['高背', '带头枕靠背'], remark: '靠背高过头部，可支撑头颈' },
    { name: '翼形包裹靠背', aliases: ['翼背', '耳朵靠背', '包围式靠背', '大象耳朵'], remark: '靠背两侧向前伸出侧翼，环抱头部' },
    { name: '分段靠包', aliases: ['多靠枕', '分离靠包', '面包块靠背', '活动靠包'], remark: '靠背由多个独立可移动靠包排列组成' },
    { name: '板面壳体靠背', aliases: ['曲木靠背', '一体板背', '贝壳靠背', '塑料壳背'], remark: '靠背为一整片无分缝的弯曲板/壳体' },
    { name: '条形/梳背靠背', aliases: ['竖条靠背', '格栅靠背', '温莎式', '竖棂'], remark: '靠背由多根竖向细条/梳齿状杆件构成，有间隙' },
    { name: 'Y形/叉骨靠背', aliases: ['叉骨椅', 'Y椅', 'Wishbone'], remark: '靠背中央为单根 Y 形（叉骨形）支撑构件' },
    { name: '编织镂空靠背', aliases: ['藤编靠背', '绳编靠背', '网面靠背'], remark: '靠背为编织/网状面，可见透空缝隙' },
    { name: '无靠背', aliases: ['无背', '榻式'], remark: '坐面之后无任何靠背构件' },
    { name: '可调节/翻折靠背', aliases: ['可调靠背', '活动头枕', '档位靠背', '可躺靠背'], remark: '可见铰链/档位结构，或靠背处于明显倾躺状态' },
    { name: '异形/其他', aliases: [], remark: '不属于以上形态' },
  ],
  C: [
    { name: '无扶手', aliases: ['光杆', '无臂'], remark: '座面两侧无任何扶手构件' },
    { name: '标准方扶手', aliases: ['直扶手', '方扶手', '常规扶手'], remark: '高度接近靠背、截面方正的常规软包扶手' },
    { name: '宽厚扶手', aliases: ['宽扶手', '厚扶手', '面包扶手', '大软垫扶手'], remark: '扶手又宽又厚，顶面可置物/坐人' },
    { name: '低扶手', aliases: ['矮扶手', '低平扶手'], remark: '扶手仅略高于座面，明显低于标准高度' },
    { name: '卷边外翻扶手', aliases: ['卷扶手', '外翻扶手', '美式卷臂'], remark: '扶手顶端向外/向前翻卷成圆卷' },
    { name: '斜面/梯形扶手', aliases: ['斜扶手', '楔形扶手'], remark: '扶手呈内斜面或上窄下宽的楔形' },
    { name: '环形/圈形扶手', aliases: ['圈扶手', '圆扶手', '环抱扶手'], remark: '扶手与靠背上沿连成连续圆环/半环' },
    { name: '细杆金属扶手', aliases: ['铁艺扶手', '金属细扶手', '线条扶手'], remark: '扶手由细圆管/扁钢线框构成' },
    { name: '木面扶手', aliases: ['实木扶手', '外露木扶手', '木框扶手'], remark: '扶手可见完整木质面（按可见外观判定，不论真实材质）' },
    { name: '一体成型扶手', aliases: ['一体扶手', '壳体扶手'], remark: '扶手与座面/靠背为同一连续壳体，无分缝' },
    { name: '异形/其他', aliases: [], remark: '不属于以上形态' },
  ],
  D: [
    { name: '落地底座', aliases: ['落地式', '无可见腿', '贴地'], remark: '座体底边直接落地，看不到任何腿' },
    { name: '实木腿', aliases: ['木腿', '实木脚', '锥形木腿'], remark: '可见四条（或更多）木质腿，常为锥形/斜撑' },
    { name: '细金属腿', aliases: ['金属细腿', '铁艺细腿', '细高脚'], remark: '纤细金属直腿/锥腿，离地间隙大' },
    { name: '敦实柱腿', aliases: ['粗腿', '方块脚', '矮粗脚'], remark: '粗短块状或柱状脚，视觉厚重' },
    { name: '金属框架底座', aliases: ['铁架底座', '外露框架', '金属骨架'], remark: '座面以下由连续钢管/扁钢框架承托，框架外露' },
    { name: '雪橇底座', aliases: ['雪橇脚', '滑橇底座', '弓形架'], remark: '金属管沿地面形成前后连续滑橇状底架' },
    { name: '悬臂底座', aliases: ['悬臂椅', 'C形架', '无后腿'], remark: '仅前部/单侧支撑，座面后端悬空无后腿' },
    { name: '中央柱底座', aliases: ['五星脚', '圆盘底座', '转椅底座', '喇叭底座', '郁金香底座'], remark: '单根中柱下接五星爪/圆盘/喇叭形底座，常可旋转' },
    { name: '摇椅底座', aliases: ['摇腿', '弧形摇脚', '摇摇椅'], remark: '底部为两根弧形摇杆，可前后摇晃' },
    { name: '悬浮底座', aliases: ['悬浮式', '内收底座', '悬空底座'], remark: '底座内收/隐藏，正视座体似漂浮（底部有阴影间隙）' },
    { name: '滚轮脚', aliases: ['带轮', '脚轮', '万向轮'], remark: '腿部末端可见滚轮' },
    { name: '异形/其他', aliases: [], remark: '不属于以上形态' },
  ],
  F: [
    { name: '光面软包', aliases: ['素面', '平整面', '无明显工艺'], remark: '表面平整绷紧，无装饰性缝迹（最常见的默认项）' },
    { name: '饱满蓬松软包', aliases: ['饱满填充', '羽绒感', '云朵感', '厚软包'], remark: '垫体鼓起外溢、边缘松垮下垂、褶皱自然' },
    { name: '薄垫紧凑软包', aliases: ['薄垫', '薄软包', '贴合坐垫'], remark: '垫体薄且紧贴框架，轮廓利落' },
    { name: '绗缝', aliases: ['车格子', '间棉', '菱形格缝线'], remark: '表面有规则缝线格纹/条纹' },
    { name: '拉扣', aliases: ['纽扣软包', '拉点', 'tufted'], remark: '表面有规律分布的内凹扣点/纽扣' },
    { name: '褶皱/抽褶', aliases: ['抓褶', '毛毛虫褶皱', '横向褶皱'], remark: '表面呈规律横向/放射状挤压褶皱' },
    { name: '分块面包块', aliases: ['面包块', '豆腐块分格', '块状软包'], remark: '座面/靠背分成若干饱满凸起的方块或长条块' },
    { name: '局部软包', aliases: ['半软包', '仅坐垫软包', '座面垫'], remark: '仅座面（或仅靠背）有软包，其余为裸露框架/硬面' },
    { name: '无软包', aliases: ['硬座', '裸面', '板面'], remark: '坐靠处为木/塑/金属硬面，无任何软垫' },
    { name: '异形/其他', aliases: [], remark: '不属于以上工艺' },
  ],
};

// A.2 TB 茶几
const LIST_TB = {
  A: [
    { name: '圆形', aliases: ['圆几', '大小圆'], remark: '俯视台面为正圆或近圆' },
    { name: '方形', aliases: ['方几', '正方形茶几'], remark: '俯视四边近等长、四角分明（含近方矩形）' },
    { name: '矩形', aliases: ['长方形茶几', '长几'], remark: '俯视明显长宽不等的直边形' },
    { name: '跑道形', aliases: ['胶囊形', '腰果形', '长圆形', '腰子形'], remark: '两端半圆+中间直边的拉长圆弧轮廓' },
    { name: '鹅卵石形', aliases: ['蛋形', '水滴形', '不规则有机形'], remark: '轮廓为无直边的自由曲线有机形' },
    { name: 'C形', aliases: ['C型边几', 'U形边几', '沙发边桌', '嵌入式边几'], remark: '侧视呈C字悬臂，底座可插入沙发/床底' },
    { name: '鼓形/墩式', aliases: ['鼓凳茶几', '圆墩茶几', '柱墩茶几'], remark: '整体为一个实心鼓/墩体，无独立细腿' },
    { name: '托盘式', aliases: ['托盘茶几', '围边茶几', '碟形茶几'], remark: '俯视整体呈碟形/托盘轮廓且台面围边上翻（围边工艺归 C 维度）' },
    { name: '组合套几', aliases: ['子母茶几', '大小组合', '套几', '高低组合'], remark: '两张以上大小/高低茶几嵌套或成组出现' },
    { name: '异形/其他', aliases: ['不规则形', '艺术造型'], remark: '无法归入上述类别的特殊轮廓' },
  ],
  B: [
    { name: '薄台面', aliases: ['薄板台面', '极简薄边'], remark: '侧视台面单薄一片（厚度相对台面宽度比例小）' },
    { name: '厚台面', aliases: ['厚板台面', '大板面'], remark: '侧视台面明显厚实有体量感' },
    { name: '悬浮台面', aliases: ['悬空台面', '漂浮台面'], remark: '台面与支撑间可见内收/缝隙，似漂浮（支撑形态正常）' },
    { name: '内嵌/下沉台面', aliases: ['内凹台面', '嵌入式台面'], remark: '面心低于边框，形成浅槽或嵌板结构' },
    { name: '双层台面', aliases: ['上下双层', '夹层台面'], remark: '可见上下两层平行台面' },
    { name: '异形拼色/拼接台面', aliases: ['拼色台面', '组合台面'], remark: '台面由两种以上材质/色块拼接' },
    { name: '其他', aliases: [], remark: '无法归类的台面构造' },
  ],
  C: [
    { name: '直边', aliases: ['直角边', '平边'], remark: '边缘为垂直利落的直切面' },
    { name: '倒角边', aliases: ['斜边', '切角边', '斜切边'], remark: '边缘可见明显斜切坡面/斜面反光带' },
    { name: '圆弧边', aliases: ['圆角边', 'R角', '磨圆边'], remark: '边缘倒圆过渡，无棱角' },
    { name: '马肚边', aliases: ['鸭嘴边', '法国边', '弧腹边'], remark: '边缘外凸成连续饱满弧线' },
    { name: '瀑布边', aliases: ['下挂边', '垂边', 'waterfall'], remark: '台面材质沿侧边垂直下延至支撑/地面' },
    { name: '自然边', aliases: ['原木边', '树皮边', '随形边'], remark: '边缘保留木材天然起伏/树皮轮廓' },
    { name: '围边', aliases: ['挡水边', '立边', '翻边', '托盘边'], remark: '边缘向上凸起一圈挡沿（托盘式茶几的围边工艺归此维度）' },
    { name: '水波纹边', aliases: ['热熔边', '波浪边', '熔岩边'], remark: '边缘呈不规则流动波浪起伏' },
    { name: '异形/其他', aliases: [], remark: '其他边缘处理' },
  ],
  D: [
    { name: '细直腿', aliases: ['细腿', '直脚', '细圆腿'], remark: '3~4根纤细垂直腿支撑' },
    { name: '锥形腿', aliases: ['锥形脚', '上粗下细腿', '斜锥腿'], remark: '腿自上而下逐渐收细' },
    { name: '外八腿', aliases: ['八字腿', '斜腿', 'A字腿'], remark: '腿向外倾斜张开呈八字' },
    { name: '粗柱腿', aliases: ['敦实柱腿', '墩柱腿', '象腿', '粗圆/方柱'], remark: '单根或多根粗壮柱状支撑' },
    { name: '金属框架', aliases: ['铁艺框架', '口字架', 'U形架', '方框腿'], remark: '金属管/板构成框式支撑' },
    { name: '交叉底座', aliases: ['X形底座', '交叉腿', '剪刀腿'], remark: '支撑件交叉成X/剪刀形' },
    { name: '单柱圆盘底座', aliases: ['郁金香底座', '喇叭底座', '独柱底盘'], remark: '中央单柱+落地圆/喇叭盘' },
    { name: '悬浮底座', aliases: ['内收底座', '隐形底座', '亚克力底座'], remark: '底座明显内收/透明，台面似悬空' },
    { name: '落地式', aliases: ['箱式底座', '落地围板', '满底'], remark: '支撑为落地箱体/围板，不见腿' },
    { name: '无腿墩式', aliases: ['整体墩', '实心墩'], remark: '整器为一落地实心墩体，无腿可辨' },
    { name: '异形/其他', aliases: [], remark: '其他支撑形态' },
  ],
  F: [
    { name: '无功能件', aliases: ['固定式', '纯台面'], remark: '无任何附加可动/储物结构（默认兜底）' },
    { name: '抽屉', aliases: ['带抽茶几'], remark: '立面可见抽屉面板/拉手' },
    { name: '层板', aliases: ['隔板', '置物层', '开放格'], remark: '台面下可见开放层板/隔层' },
    { name: '升降台面', aliases: ['升降茶几', 'Lift-top', '可升桌板'], remark: '台面可抬升，可见铰链/气压杆结构' },
    { name: '旋转功能件', aliases: ['旋转台面', '转动盘', '旋转层'], remark: '可见可转动圆盘/旋转层结构' },
    { name: '折叠', aliases: ['折叠茶几', '翻折面'], remark: '可见折叠铰链/可收折的腿或面' },
    { name: '滚轮', aliases: ['带轮茶几', '移动茶几'], remark: '底部可见脚轮/万向轮' },
    { name: '套叠收纳', aliases: ['可叠放', '嵌套收纳'], remark: '小几可完全收入大几之下' },
    { name: '其他', aliases: [], remark: '其他可见功能件' },
  ],
};

// A.3 DT 餐桌（v2.0 新增品类）
const LIST_DT = {
  A: [
    { name: '长桌', aliases: ['长方形餐桌', '条桌', '长条桌'], remark: '俯视为长矩形，市场绝对主力' },
    { name: '圆桌', aliases: ['圆餐桌', '大圆桌'], remark: '俯视为正圆' },
    { name: '方桌', aliases: ['方餐桌', '八仙桌', '四人方桌'], remark: '俯视四边等长' },
    { name: '椭圆桌', aliases: ['椭圆形餐桌', '蛋形桌'], remark: '俯视为规则椭圆' },
    { name: '跑道形', aliases: ['胶囊形', '腰果形', '长圆桌'], remark: '两端半圆+直边的拉长轮廓' },
    { name: '半圆桌', aliases: ['半月桌', '靠墙半圆'], remark: '一侧直边靠墙、一侧半圆' },
    { name: '岛台一体桌', aliases: ['岛台餐桌', '餐岛一体', '中岛台'], remark: '桌与厨房岛台连成一体的组合形态' },
    { name: '吧台桌', aliases: ['吧桌', '高脚桌', '高吧桌'], remark: '明显高台面（约90cm及以上）配高脚凳' },
    { name: '异形/其他', aliases: ['不规则桌'], remark: '其他轮廓' },
  ],
  B: [
    { name: '平板薄面', aliases: ['薄边平板', '薄板台面'], remark: '侧视台面单薄平整' },
    { name: '厚台面', aliases: ['厚板', '大板台面'], remark: '侧视台面厚实有分量' },
    { name: '悬浮台面', aliases: ['悬空台面'], remark: '台面与底座间内收/留缝似漂浮' },
    { name: '转盘台面', aliases: ['带转盘桌面', '双层圆面', '旋转餐盘'], remark: '圆桌面中央可见可转动转盘（转盘特征统一归此维度）' },
    { name: '翻板台面', aliases: ['蝶形翻板', '折叠面板'], remark: '桌面可见翻折板与铰链拼缝' },
    { name: '拼缝台面', aliases: ['拼板台面', '伸缩缝面'], remark: '桌面中部可见伸缩拼接缝/轨道线' },
    { name: '内嵌台面', aliases: ['嵌板面', '框中嵌面'], remark: '面板嵌入边框，材质混搭' },
    { name: '围边台面', aliases: ['挡边面', '托盘面'], remark: '桌面边缘上翻有围挡' },
    { name: '其他', aliases: [], remark: '其他台面构造' },
  ],
  C: [
    { name: '直边', aliases: ['直角边', '平边'], remark: '边缘垂直利落' },
    { name: '圆角边', aliases: ['圆弧边', 'R角', '磨圆边'], remark: '角部/边缘倒圆' },
    { name: '倒角边', aliases: ['斜边', '切角边'], remark: '边缘可见斜切坡面' },
    { name: '马肚边', aliases: ['鸭嘴边', '弧腹边', '法国边'], remark: '边缘外凸成饱满连续弧线' },
    { name: '瀑布边', aliases: ['下挂边', '垂边', 'waterfall edge'], remark: '台面材质沿侧边垂直下延' },
    { name: '自然边', aliases: ['原木边', '随形边'], remark: '保留木材天然轮廓的边缘' },
    { name: '裙边/立水', aliases: ['围板', '牙板', '束腰'], remark: '台面下沿有一圈可见围板/牙条结构' },
    { name: '异形/其他', aliases: [], remark: '其他边缘/结构' },
  ],
  D: [
    { name: '四直腿', aliases: ['直腿', '四方腿', '立柱腿'], remark: '四角各一根垂直腿' },
    { name: '外八腿', aliases: ['八字腿', '斜腿', 'A字腿'], remark: '腿向外张开呈八字' },
    { name: '锥形腿', aliases: ['锥形脚', '收细腿'], remark: '腿上粗下细逐渐收分' },
    { name: '喇叭/郁金香底座', aliases: ['喇叭腿', '郁金香脚', '独柱圆盘'], remark: '中央单柱下接喇叭形圆盘' },
    { name: '粗柱腿', aliases: ['大象腿', '墩柱腿', '粗方/圆柱'], remark: '粗壮柱状腿，体量感强' },
    { name: 'T形/一字底座', aliases: ['T字腿', '一字脚架'], remark: '两端各一T字/一字横脚支撑' },
    { name: '工字/H形底座', aliases: ['工字架', 'H形腿'], remark: '侧视呈工/H形的框架支撑' },
    { name: '交叉底座', aliases: ['X形底座', '交叉腿', '叉骨腿'], remark: '支撑交叉成X形' },
    { name: 'U形/口字框架', aliases: ['口字腿', 'U形架', '框式腿'], remark: '两端各一封闭框式支撑' },
    { name: '悬浮/内收底座', aliases: ['悬浮底座', '隐形底座'], remark: '底座深内收或透明，桌面似悬空' },
    { name: '落地箱式', aliases: ['箱体底座', '岛台落地柜'], remark: '支撑为落地柜体/箱体' },
    { name: '异形/其他', aliases: [], remark: '其他支撑形态' },
  ],
  F: [
    { name: '固定式', aliases: ['不可伸缩', '整板'], remark: '桌面一整块，无变形结构' },
    { name: '伸缩式', aliases: ['抽拉伸缩', '导轨伸缩', '加长桌'], remark: '桌面可沿导轨拉开加长（可见伸缩缝/导轨）' },
    { name: '折叠式', aliases: ['折叠桌', '翻板桌', '蝶形折叠'], remark: '桌板/腿可翻折收合，可见铰链' },
    { name: '旋转展开', aliases: ['旋转变径', '旋转伸缩圆桌'], remark: '圆桌旋开后拼板展开变大' },
    { name: '升降', aliases: ['升降餐桌', '茶几餐桌两用'], remark: '桌面高度可调（气压/电动柱可见）' },
    { name: '带储物', aliases: ['带抽屉', '带柜餐桌'], remark: '桌体可见抽屉/柜门' },
    { name: '带电器件', aliases: ['电磁炉餐桌', '暖菜板桌', '火锅桌'], remark: '桌面可见嵌入式电磁炉/暖菜板/插座面板' },
    { name: '带滚轮', aliases: ['移动餐桌', '带轮岛台'], remark: '底部可见脚轮' },
    { name: '其他', aliases: [], remark: '其他可见功能' },
  ],
};

// A.4 FC 柜类
const LIST_FC = {
  A: [
    { name: '矮柜', aliases: ['地柜', '半高柜', '矮边柜', '低柜'], remark: '高度齐腰及以下、横长比例的独立柜体' },
    { name: '高柜', aliases: ['立柜', '通顶柜', '到顶柜', '一门到顶'], remark: '高度明显超过人胸/到顶、竖长比例' },
    { name: '组合柜', aliases: ['高低组合柜', '模块柜', '电视墙柜', '满墙柜'], remark: '多个柜体单元拼接、高低错落或满墙一体' },
    { name: '斗柜', aliases: ['三斗柜', '四斗柜', '五斗柜', '多斗柜'], remark: '竖向或横向叠放多个等大抽屉、无门或少量门' },
    { name: '转角柜', aliases: ['L型柜', '角柜', '拐角柜', '三角柜'], remark: '贴合两面墙转角、俯视呈L形或三角形' },
    { name: '弧形柜', aliases: ['圆弧柜', '圆角柜', '弧形边柜', '拱形柜'], remark: '侧板或转角为圆弧曲面而非直角' },
    { name: '隔断柜', aliases: ['博古架柜', '双面柜', '镂空置物柜'], remark: '柜体通透双面可用、作空间分隔' },
    { name: '其他', aliases: [], remark: '无法归入以上形态' },
  ],
  B: [
    { name: '平板门', aliases: ['光板门', '双饰面门', 'PET门板', '肤感门'], remark: '门面平整无造型、无压线' },
    { name: '造型门', aliases: ['吸塑门', '模压门', '拼框门', '法式线条门', '回字门'], remark: '门面带内凹/凸起的框线造型' },
    { name: '骨骼线门', aliases: ['骨骼门', '外凸线条门', '井字/回字线条门'], remark: '门板表面有外凸装饰木线条且常兼作拉手' },
    { name: '格栅门', aliases: ['竖条纹门', '木格栅门', '栅格门', '长城板门'], remark: '门面为连续竖向凸条纹或镂空格栅' },
    { name: '藤编门', aliases: ['藤面门', '藤编框门', '编藤柜门'], remark: '门框内嵌编织藤面、可见经纬编织纹' },
    { name: '长虹玻璃门', aliases: ['竖纹玻璃门', '瓦楞玻璃门'], remark: '玻璃面带竖向压花条纹、朦胧透光' },
    { name: '玻璃门', aliases: ['清玻门', '灰玻门', '茶玻门', '铝框玻璃门'], remark: '透明/有色平玻璃、柜内物品可见' },
    { name: '移门', aliases: ['推拉门', '趟门', '滑门'], remark: '门板左右滑轨平移开启、有重叠门扇' },
    { name: '开放格为主', aliases: ['敞口柜', '格子柜', '无门柜'], remark: '立面大部分为无门敞口格' },
    { name: '抽屉为主', aliases: ['全抽屉柜', '多抽柜'], remark: '立面大部分为抽屉面板' },
    { name: '其他', aliases: ['百叶门', '软包门'], remark: '百叶门、软包门等少见形式' },
  ],
  C: [
    { name: '明装拉手', aliases: ['外装拉手', '明拉手', '圆钮/长条/黄铜把手'], remark: '拉手凸出安装于门板表面' },
    { name: '无拉手', aliases: ['反弹器', '按压弹开', '碰碰开'], remark: '门面完全平整无任何拉手/凹槽' },
    { name: '铣槽拉手', aliases: ['凹槽拉手', 'J型/C型槽', '牛角槽', '一字槽'], remark: '门板边或面上铣出同色暗槽作抠手' },
    { name: '斜切拉手', aliases: ['45°斜切', '斜边拉手', '切角拉手'], remark: '门板上/下沿45°斜切留缝作抠手位' },
    { name: 'G型拉手', aliases: ['G型/L型/U型金属型材拉手', '内嵌型材拉手'], remark: '柜体层板间嵌金属型材形成通长拉槽' },
    { name: '门板下延', aliases: ['门板下挂', '门板加长', '上延抠手'], remark: '门板比柜体长1-2cm，抠延伸边开门' },
    { name: '隐形拉手', aliases: ['线性隐形拉手', '拇指拉手', '嵌入式拉手'], remark: '门缝处极窄长条、存在感极低' },
    { name: '其他', aliases: ['皮拉手', '旋转拉手'], remark: '皮拉手、旋转拉手等' },
  ],
  D: [
    { name: '落地式', aliases: ['落地柜', '围板落地', '踢脚板底座'], remark: '柜体直接落地、底部为围板/踢脚线' },
    { name: '高脚', aliases: ['细高腿', '锥形木脚', '实木脚'], remark: '四只细长脚抬高柜体、底部大空隙' },
    { name: '金属支脚', aliases: ['金属脚', '不锈钢脚', '金色细脚', '铁艺脚'], remark: '金属材质细脚或框架脚' },
    { name: '矮脚', aliases: ['小矮脚', '方墩脚', '离地缝脚'], remark: '脚高不超过15cm、留缝可过扫地机' },
    { name: '悬浮挂墙', aliases: ['挂墙柜', '壁挂柜', '悬空柜', '吊柜'], remark: '柜体固定上墙、底部完全悬空' },
    { name: '带轮', aliases: ['万向轮', '滑轮柜', '移动柜'], remark: '底部可见滚轮、可移动' },
    { name: '其他', aliases: ['旋转底座'], remark: '旋转底座等少见形式' },
  ],
  F: [
    { name: '隔层', aliases: ['层板', '可调层板', '隔板分隔'], remark: '内部以水平层板分隔空间' },
    { name: '抽屉', aliases: ['内置抽屉', '抽内分隔'], remark: '门内或外露抽屉收纳' },
    { name: '设备位', aliases: ['视听位', '机顶盒位', '走线孔', '插座位'], remark: '可见开放设备格、背板走线孔/插座' },
    { name: '酒架杯架', aliases: ['红酒格', '酒格', '酒杯挂架'], remark: '可见X/方格酒架或高脚杯倒挂架' },
    { name: '鞋柜结构', aliases: ['斜插鞋架', '翻斗鞋柜', '翻转鞋架'], remark: '斜放鞋位或下翻斗门结构' },
    { name: '台面功能区', aliases: ['操作台', '水吧台', '轨道插座', '咖啡角'], remark: '中部留空台面+背板插座/管线位' },
    { name: '灯带', aliases: ['感应灯', '氛围灯带', '展示灯'], remark: '层板下/柜内可见发光灯带' },
    { name: '挂物区', aliases: ['挂衣钩', '洞洞板', '挂杆'], remark: '开放挂衣/挂物区' },
    { name: '其他', aliases: ['旋转鞋架', '抽拉台面'], remark: '旋转鞋架、抽拉台面等' },
  ],
};

// A.5 BD 床（v2.0 新增品类）
const LIST_BD = {
  A: [
    { name: '齐边床', aliases: ['齐边设计', '窄边床', '省空间床'], remark: '床边与床垫基本齐平、无外扩床框' },
    { name: '内嵌床', aliases: ['包边床', '宽边床', '床垫内嵌床'], remark: '床垫陷入床框、四周有明显宽床沿' },
    { name: '地台床', aliases: ['榻榻米床', '落地矮床', '无腿床'], remark: '低矮落地台座、床垫直接置于地台' },
    { name: '箱体床', aliases: ['箱框床', '厚床身床', '高床体床'], remark: '床身整体厚实落地、呈箱子轮廓' },
    { name: '上下床', aliases: ['高低床', '双层床', '子母床', '上下铺'], remark: '上下两层床面+爬梯/梯柜' },
    { name: '半高床/高架床', aliases: ['中高床', '上床下桌', '上床下柜'], remark: '床面抬高、床下为书桌/柜/活动空间' },
    { name: '异形造型床', aliases: ['汽车床', '房子床', '城堡床', '圆床'], remark: '整体为卡通/非常规几何造型' },
    { name: '其他', aliases: ['折叠床', '壁床', '墨菲床'], remark: '折叠床、壁床（墨菲床）等' },
  ],
  B: [
    { name: '软包大靠包', aliases: ['大靠枕', '双靠包', '饱满靠包', '分段靠包'], remark: '床头为1-2个饱满突出的软靠包' },
    { name: '拉扣床头', aliases: ['拉点床头', '纽扣床头', '法式拉扣', '铆钉床头'], remark: '软包表面有规则凹点纽扣拉花' },
    { name: '竖琴床头', aliases: ['竖琴床', '温莎床', '竖条床头', '栅栏床屏'], remark: '床头由竖向细条/立柱排列构成' },
    { name: '平板薄床头', aliases: ['超薄床头', '极简床屏', '直板床头'], remark: '床头为薄而平整的一整块板/软包面' },
    { name: '折耳靠包', aliases: ['大象耳朵', '象耳床', '翻折耳朵', 'Baxter象耳'], remark: '靠包两侧可翻折下垂如大象耳朵' },
    { name: '信封床头', aliases: ['信封床', '信封翻折靠头', '皮带扣床头'], remark: '软包如信封翻折、饰皮带/五金扣' },
    { name: '云朵床头', aliases: ['云朵床', '花瓣床头', '波浪软包'], remark: '床屏轮廓为圆润云朵/花瓣曲线' },
    { name: '拱形床头', aliases: ['拱门床屏', '法式拱门', '圆弧床头'], remark: '床屏顶部为拱形/大圆弧线' },
    { name: '卡通造型床头', aliases: ['猫耳床', '兔耳床', '皇冠床头'], remark: '床头带动物耳朵/卡通轮廓' },
    { name: '功能床头', aliases: ['置物床头', '书架床头', '储物床屏'], remark: '床屏带置物格/开放架/插座夜灯' },
    { name: '无床头', aliases: ['无床屏', '裸床架', '榻榻米床'], remark: '无床头板、床尾床头同高或靠墙' },
    { name: '其他', aliases: ['屏风式', '超宽屏床头'], remark: '屏风式、超宽屏床头等' },
  ],
  C: [
    { name: '齐边无床尾', aliases: ['无床尾屏', '低床尾', '齐平床尾'], remark: '床尾与床垫齐平或更低、无遮挡' },
    { name: '高床尾屏', aliases: ['床尾板', '美式床尾', '高尾屏'], remark: '床尾有明显高出的屏板' },
    { name: '立柱床尾', aliases: ['罗马柱床', '四柱床', '床尾柱'], remark: '床尾带装饰立柱' },
    { name: '软包床尾', aliases: ['软包尾板', '床尾凳一体'], remark: '床尾为软包面或与床体同面料' },
    { name: '宽边床沿', aliases: ['宽床沿', '可坐床边', '平台床边'], remark: '床侧床沿宽大可坐可置物' },
    { name: '圆角床边', aliases: ['圆弧收边', '防撞圆边', '圆润转角'], remark: '床边转角为圆弧无棱角' },
    { name: '铁艺床尾', aliases: ['金属管床尾', '铁艺花纹床围'], remark: '床尾为铁艺管材/花纹' },
    { name: '其他', aliases: ['弧形床尾', '船型床尾'], remark: '弧形床尾、船型床尾等' },
  ],
  D: [
    { name: '实木脚', aliases: ['木腿', '锥形木脚', '实木床脚'], remark: '可见木质支脚（含中脚）' },
    { name: '金属脚', aliases: ['金属细脚', '不锈钢脚', '碳素钢脚', '金色脚'], remark: '可见金属材质支脚' },
    { name: '矮脚', aliases: ['小矮脚', '短脚', '离地缝脚'], remark: '床底仅留小缝隙（约5-15cm）' },
    { name: '落地无脚', aliases: ['全落地', '围边落地', '床裙落地'], remark: '床体四周直接落地不见脚' },
    { name: '悬浮底座', aliases: ['内收底座', '悬浮床脚', '灯带底座', '悬浮床剪影'], remark: '支脚内缩视觉悬浮、常配床底灯（悬浮特征统一归此维度）' },
    { name: '排骨架床架', aliases: ['排骨架', '床条架', '卷闸排骨条'], remark: '床面由横向木条排列构成（无床垫图可见时适用）' },
    { name: '其他', aliases: ['万向轮脚', '气压升降脚'], remark: '万向轮脚、气压升降脚等' },
  ],
  F: [
    { name: '无储物', aliases: ['框架床', '空床底', '普通床架'], remark: '床底通透或封闭但无任何储物开启结构' },
    { name: '气压上掀储物', aliases: ['高箱床', '气压杆床', '液压箱体床', '油压床'], remark: '床板连床垫整体可上掀、床体为大箱仓' },
    { name: '床体抽屉', aliases: ['侧抽床', '床尾抽屉', '三抽储物床'], remark: '床侧/床尾可见抽屉面板与拉手缝' },
    { name: '床头功能区', aliases: ['置物床头', '充电床头', '书架床头', '夜灯床头'], remark: '床屏带格架/插座/灯等可见功能件' },
    { name: '床底灯带', aliases: ['悬浮灯', '感应夜灯', '氛围灯'], remark: '床底沿可见灯带发光' },
    { name: '组合功能床', aliases: ['上床下桌', '梯柜床', '床柜一体', '榻榻米组合'], remark: '床与书桌/梯柜/衣柜连成一体' },
    { name: '拖床', aliases: ['拖拉子床', '抽拉床', '子母拖床'], remark: '主床下藏可拉出的小床' },
    { name: '其他', aliases: ['电动床架', '按摩功能'], remark: '电动床架、按摩功能等' },
  ],
};

// A.6 BS 吧椅
const LIST_BS = {
  A: [
    { name: '圆形座', aliases: ['圆凳面', '圆盘座', '圆面吧凳'], remark: '座面俯视呈正圆或椭圆形，无方向性' },
    { name: '方形座', aliases: ['方凳面', '矩形座', '方座'], remark: '座面俯视呈正方形或矩形，可见直边直角' },
    { name: '曲壳座', aliases: ['曲木座', '弯板座', '一体壳座', 'PP座壳'], remark: '座面为一体化成型曲面壳体，带人体工学下凹弧度' },
    { name: '马鞍座', aliases: ['鞍形座', '马鞍凳', 'W形座'], remark: '座面呈马鞍状前后翘起、中间下凹的W双曲面' },
    { name: '镂空铁座', aliases: ['拖拉机座', '拖拉机凳', '铸铁座', '工业风座'], remark: '金属座面两侧凸起带镂空孔洞，形似老式拖拉机座' },
    { name: '马蹄形座', aliases: ['马蹄座', 'U形座', '半圆口座'], remark: '座面后缘或前缘带U形/马蹄形缺口或轮廓' },
    { name: '其他', aliases: [], remark: '不属于以上任何形态的座面' },
  ],
  B: [
    { name: '无靠背', aliases: ['无背', '光凳', '吧凳'], remark: '座面上方完全无竖向支撑结构' },
    { name: '低靠背', aliases: ['半靠背', '矮靠背', '腰靠'], remark: '靠背高度仅及腰部，明显低于肩胛' },
    { name: '高靠背', aliases: ['全靠背', '高背吧椅'], remark: '靠背向上延伸至肩胛及以上，形成完整背部支撑面' },
    { name: '环抱式靠背', aliases: ['环绕靠背', '一体壳背', '天鹅椅式', '蝴蝶背'], remark: '靠背呈弧形向前环抱包覆，与座壳连成有机曲面' },
    { name: '竖条靠背', aliases: ['梳背', '温莎背', '条背'], remark: '靠背由多根竖向细条排列构成，条间可见缝隙' },
    { name: '镂空网格靠背', aliases: ['镂空背', '铁艺背', '网格背', '冲孔背'], remark: '靠背为带规则或不规则镂空图案的板面/网格' },
    { name: '编织靠背', aliases: ['藤编背', '绳编背', '编带背'], remark: '靠背可见藤条/绳/织带交叉编织纹理' },
    { name: '其他', aliases: [], remark: '不属于以上任何形态的靠背' },
  ],
  C: [
    { name: '无扶手', aliases: ['光身', '无臂'], remark: '座面两侧无任何供手臂搭放的结构' },
    { name: '双扶手', aliases: ['两侧扶手', '独立扶手', '全扶手'], remark: '座面左右各有一根独立于靠背的扶手杆/板' },
    { name: '一体环绕扶手', aliases: ['一体扶手', '环抱扶手', '壳式扶手'], remark: '扶手与靠背由同一曲面/杆件连续环绕成型，无断点' },
    { name: '小扶手', aliases: ['半扶手', '短扶手', '半截扶手'], remark: '扶手长度明显短于座面深度，仅覆盖后半段或呈短柱状' },
    { name: '环形扶手', aliases: ['圆环扶手', '皇冠扶手'], remark: '扶手为一整圈环形杆件环绕座面上方（低频，注意与座下脚踏圈区分）' },
    { name: '其他', aliases: [], remark: '不属于以上任何形态的扶手' },
  ],
  D: [
    { name: '气压升降底座', aliases: ['气压杆', '升降底座', '气杆圆盘'], remark: '座下可见单根金属气压柱+圆形平底盘，常带环形脚踏圈' },
    { name: '四脚底座', aliases: ['四条腿', '木脚', '四腿架'], remark: '四根独立椅腿支撑，腿间常有横撑（踏脚撑）' },
    { name: '单柱圆盘底座', aliases: ['固定圆盘', '喇叭底座', '郁金香脚', '圆盘脚'], remark: '单根立柱下接一体成型圆盘/喇叭形盘，不可升降' },
    { name: '五星脚底座', aliases: ['五爪脚', '五星脚', '带轮底座'], remark: '中心柱下伸出五爪支脚且末端带滚轮' },
    { name: '螺旋升降底座', aliases: ['螺旋杆', '旋转升降', '丝杆升降'], remark: '座面靠螺纹丝杆旋转调节高度，座下可见螺杆结构' },
    { name: '雪橇脚底座', aliases: ['弓形脚', '滑橇脚', '钢筋弓架'], remark: '钢管弯曲成落地滑橇状连贯底架' },
    { name: '三脚底座', aliases: ['三腿', '三角架'], remark: '三根支腿呈三角分布支撑座面' },
    { name: '其他', aliases: [], remark: '不属于以上任何形态的底座' },
  ],
  F: [
    { name: '无软包', aliases: ['硬面', '光板', '素面'], remark: '座面/靠背为裸露木、金属、塑料或藤面，无织物皮革覆盖' },
    { name: '薄垫', aliases: ['薄软包', '平板垫', '贴面垫'], remark: '座面覆一层扁平垫层，厚度薄、轮廓贴合座面' },
    { name: '厚软包', aliases: ['厚垫', '饱满软包', '面包座'], remark: '垫层明显隆起饱满，边缘可见鼓胀体量' },
    { name: '绗缝', aliases: ['车线格纹', '菱形格', '竖条绗缝', '拉线'], remark: '软包表面有规则缝线分割出的格纹/条纹肌理' },
    { name: '拉扣', aliases: ['拉点', '纽扣软包', 'Chesterfield'], remark: '软包表面有纽扣下陷形成的均匀凹点与放射褶皱' },
    { name: '其他', aliases: [], remark: '不属于以上任何形态的软包' },
  ],
};

// A.7 OF 办公家具（A 维度承担"二级品类细分"职责）
const LIST_OF = {
  A: [
    { name: '办公椅', aliases: ['职员椅', '转椅', '电脑椅', '老板椅', '会议椅'], remark: '带靠背与底座的单人居坐家具' },
    { name: '职员桌', aliases: ['员工桌', '电脑桌', '开放式工位', '办公桌'], remark: '单人/多人开放式条形工作桌，无围合屏风' },
    { name: '屏风工位', aliases: ['卡位', '卡座', '隔断工位', '屏风桌'], remark: '桌面被高于台面的屏风板半围合，形成独立格子间' },
    { name: '文件柜', aliases: ['资料柜', '书柜', '档案柜', '铁皮柜', '储物柜'], remark: '以竖向柜体与门/抽屉为主的储物家具，无工作台面' },
    { name: '会议桌', aliases: ['会议台', '洽谈长桌'], remark: '可供多人围坐的长条/圆形大台面桌' },
    { name: '班台', aliases: ['大班台', '老板桌', '总裁桌', '大班桌'], remark: '体量大、台面宽厚、带落地侧板与副柜的独立 executive 桌' },
    { name: '主管桌', aliases: ['经理桌', '主管台'], remark: '体量介于班台与职员桌之间，常带小侧柜' },
    { name: '培训折叠桌', aliases: ['折叠桌', '条桌', '翻板桌', '培训桌'], remark: '桌腿或台面可折叠/翻转，便于收纳拼接' },
    { name: '洽谈桌', aliases: ['洽谈台', '小圆桌', '谈判桌'], remark: '小尺度圆/方台面，供2~4人近距离对坐' },
    { name: '升降桌', aliases: ['电动升降桌', '站立办公桌'], remark: '可见粗壮双立柱升降腿，台面高度可调' },
    { name: '其他', aliases: ['前台接待台', '讲台'], remark: '不属于以上任何品类形态' },
  ],
  B: [
    { name: '一字台面', aliases: ['平面台面', '矩形台面', '直台面'], remark: '工作面为单一矩形平面，无转角无附加板' },
    { name: 'L型台面', aliases: ['转角台面', 'L台', '拐角台面'], remark: '工作面由两个方向台面垂直相接成L形' },
    { name: '弧形台面', aliases: ['鸭嘴边', '弧边台', '异型台缘'], remark: '台面前缘呈外凸弧线或波浪形而非直线' },
    { name: '带挡板', aliases: ['前挡板', '桌挡', '屏风挡板'], remark: '台面前缘下方或上方有竖直挡板遮挡视线' },
    { name: '网布靠背', aliases: ['网背', '透气网背', '全网'], remark: '椅背为绷紧的半透明网状织物，可透见网格纹理' },
    { name: '软包靠背', aliases: ['皮背', '布背', '海绵靠背'], remark: '椅背为皮革/织物包裹海绵的实心软包面' },
    { name: '硬壳靠背', aliases: ['塑壳背', '曲木背', '一体壳背'], remark: '椅背为硬质一体成型壳体，无软包无网面' },
    { name: '玻璃柜门', aliases: ['玻璃门书柜', '玻门柜'], remark: '柜体正面为透明/半透明玻璃门扇，可透视内部' },
    { name: '封闭柜门', aliases: ['掩门', '铁门', '木门', '实门柜'], remark: '柜体正面为不透明实体门扇' },
    { name: '其他', aliases: [], remark: '不属于以上任何工作面/背部形态' },
  ],
  C: [
    { name: '落地侧板', aliases: ['侧板', '封板', '台脚板'], remark: '桌体两侧为从台面直达地面的整板支撑面' },
    { name: '副柜侧柜', aliases: ['副台', '附柜', '侧柜', '活动侧柜'], remark: '主台侧面依附连接的低柜/窄台面单元' },
    { name: '屏风隔断', aliases: ['屏风板', '隔断板', '卡位屏风'], remark: '工位之间/边缘竖立的高于台面的分隔板' },
    { name: '扶手', aliases: ['椅扶手', '升降扶手', '固定扶手'], remark: '椅座两侧供手臂搭放的杆状/面状结构' },
    { name: '椅背侧翼', aliases: ['侧翼', '护翼', '包围翼'], remark: '椅背两侧向前包出的翼状凸起' },
    { name: '走线槽盒', aliases: ['线槽', '线盒', '过线盒', '走线孔盖'], remark: '台面或桌下可见的矩形走线槽/翻盖线盒' },
    { name: '横梁拉杆', aliases: ['桌下横撑', '拉杆', '连接梁'], remark: '桌腿之间可见的水平连接杆件' },
    { name: '其他', aliases: [], remark: '不属于以上任何侧部/连接特征' },
  ],
  D: [
    { name: '钢架桌腿', aliases: ['金属桌架', '钢架', '口字架', '钢木腿'], remark: '金属管材焊接成口字/框形桌架承托台面' },
    { name: '板式落地支撑', aliases: ['落地侧板脚', '全落地', '板脚'], remark: '由竖直板材直达地面形成支撑，无独立细腿' },
    { name: '实木桌腿', aliases: ['木腿', '实木框架脚'], remark: '木质方/圆腿或木框架支撑' },
    { name: '升降立柱腿', aliases: ['升降柱', '电动腿', '双柱腿'], remark: '两条粗壮矩形立柱套筒式桌腿，区别于细管钢架' },
    { name: '五星脚底盘', aliases: ['五爪脚', '五星脚', '转椅底盘'], remark: '中心气压柱下伸出五爪支脚并带滚轮' },
    { name: '弓形脚', aliases: ['悬臂脚', '弓字脚', '弓架椅'], remark: '钢管弯成前悬后弓的C/弓形，无后腿' },
    { name: '四脚底座', aliases: ['四腿', '四脚椅腿'], remark: '四根独立椅腿/桌腿垂直支撑' },
    { name: '柜类落地底座', aliases: ['柜脚', '踢脚底', '落地柜'], remark: '柜体直接落地或带矮踢脚/小柜脚' },
    { name: '其他', aliases: [], remark: '不属于以上任何支撑形态' },
  ],
  F: [
    { name: '无功能件', aliases: ['素体', '无附件'], remark: '整桌/整椅无任何附加功能构件' },
    { name: '抽屉', aliases: ['吊抽', '桌斗', '斗抽'], remark: '台面下方或柜体正面可见抽屉面板与拉手' },
    { name: '升降机构', aliases: ['气压杆', '升降柱', '手摇升降'], remark: '可见气压杆手柄/电动柱/摇把等调高构件' },
    { name: '头枕', aliases: ['头靠', '颈枕', '可调节头枕'], remark: '椅背顶部凸出的独立小枕面' },
    { name: '腰靠', aliases: ['腰托', '腰枕', '撑腰'], remark: '椅背腰部位置独立凸起或可调的支撑件' },
    { name: '脚踏', aliases: ['搁脚', '脚托', '躺舒宝'], remark: '椅座前方可抽出/翻出的腿部承托板' },
    { name: '活动柜', aliases: ['移动推柜', '三抽柜', '桌下柜'], remark: '桌下带轮可移动的独立小柜' },
    { name: '键盘架', aliases: ['键盘托', '键盘抽'], remark: '台面下方可抽拉的窄托板' },
    { name: '软包坐垫', aliases: ['海绵坐垫', '厚坐垫'], remark: '椅座为明显鼓起的软包垫层（与 B 软包靠背区分：一座一背）' },
    { name: '其他', aliases: ['杯架', '书报架'], remark: '不属于以上任何功能件' },
  ],
};

// A.8 LT 灯具（v2.0 新增品类）
const LIST_LT = {
  A: [
    { name: '球形', aliases: ['圆球灯', '球泡灯', '球体灯'], remark: '灯体主体为正圆球/半球形发光体' },
    { name: '圆盘形', aliases: ['飞碟灯', '碟形', '平板灯', '面板灯'], remark: '灯体为扁平圆盘/薄板状，厚度远小于直径' },
    { name: '长条形', aliases: ['线性灯', '一字灯', '长条吊灯', '灯管形'], remark: '灯体呈细长直线状，长度远大于宽度' },
    { name: '环形', aliases: ['圈圈灯', '圆环灯', '光环灯'], remark: '灯体为一个或多个同心发光圆环' },
    { name: '枝形', aliases: ['枝形吊灯', '多臂吊灯', '烛台吊灯'], remark: '中心灯柱向外分出多个弯曲灯臂，每臂一端灯' },
    { name: '伞形', aliases: ['斗笠灯', '草帽灯', '伞盖灯'], remark: '灯罩呈上小下大的伞盖/斗笠轮廓，光向下投' },
    { name: '蘑菇形', aliases: ['蘑菇灯'], remark: '半球伞盖+圆柱灯梗构成蘑菇剪影' },
    { name: '分子式', aliases: ['分子灯', '魔豆灯', '多头球灯', '卫星灯'], remark: '主杆上不规则伸展多支杆，各端带球形灯头' },
    { name: '柱形', aliases: ['筒形灯', '圆柱灯', '直筒灯'], remark: '灯体为直立圆柱/方柱筒状' },
    { name: '笼形', aliases: ['鸟笼灯', '铁笼灯', '笼式灯'], remark: '光源被金属条/藤条编织的笼状外壳包围' },
    { name: '仿生异形', aliases: ['花形灯', '云朵灯', '艺术造型灯'], remark: '灯体模拟花朵/云/动植物或呈不规则艺术形态' },
    { name: '其他', aliases: [], remark: '不属于以上任何灯体造型' },
  ],
  B: [
    { name: '玻璃罩', aliases: ['玻璃灯罩', '磨砂玻璃', '奶白玻璃罩'], remark: '透明/磨砂/乳白色玻璃罩体，可见玻璃质感与透光' },
    { name: '亚克力罩', aliases: ['亚克力灯罩', '导光板', 'PS罩'], remark: '白色半透明塑料质感罩体，边缘可见均匀导光面' },
    { name: '金属罩', aliases: ['铁艺罩', '金属灯罩', '铝罩'], remark: '不透明金属罩壳，光仅从开口定向射出' },
    { name: '布艺罩', aliases: ['布罩', '麻布灯罩', '棉麻罩'], remark: '织物绷面罩体，可见布纹肌理、边缘包边' },
    { name: '无罩裸光源', aliases: ['裸灯泡', '爱迪生灯泡', '灯带一体', '灯盘'], remark: '光源（灯泡/灯带/灯珠板）完全外露无罩体遮挡' },
    { name: '褶皱罩', aliases: ['百褶灯罩', '折纸罩', '风琴罩'], remark: '罩面呈规则放射状打褶的风琴式立体纹理' },
    { name: '藤竹编织罩', aliases: ['藤编灯罩', '竹编罩', '草编罩'], remark: '罩体由藤/竹/草条编织而成，可见编织孔洞与漏光' },
    { name: '纸质罩', aliases: ['纸灯', '和纸灯', '羊皮纸罩'], remark: '纸质半透明罩体，质感轻盈哑光' },
    { name: '水晶罩串', aliases: ['水晶灯罩', '水晶珠串罩', '玻璃串珠'], remark: '出光部位由水晶/玻璃珠串或切割水晶件构成（看罩体本身）' },
    { name: '其他', aliases: ['陶瓷罩'], remark: '不属于以上任何罩体/出光形态' },
  ],
  C: [
    { name: '吊线吊杆', aliases: ['吊线', '吊杆', '直吊', '吊链杆'], remark: '灯体由单根/多根竖直线缆或刚性杆从顶面垂吊' },
    { name: '无臂直连', aliases: ['直连', '贴装', '一体化'], remark: '灯体直接贴合安装面，中间无任何杆臂结构' },
    { name: '多枝灯臂', aliases: ['分叉灯臂', '曲臂', '枝臂'], remark: '多根弯曲/伸展灯臂从中心向外连接各灯头' },
    { name: '直杆立杆', aliases: ['灯柱', '直杆', '落地杆'], remark: '底座向上延伸一根竖直长杆支撑顶部灯头' },
    { name: '弧形悬臂', aliases: ['钓鱼竿', '抛物线臂', '钓鱼灯臂'], remark: '长臂呈大跨度抛物线弧，灯头悬垂于弧端' },
    { name: '折叠摇臂', aliases: ['长臂折叠', '摇臂', '机械臂', '弹簧臂'], remark: '由关节连接的两段以上杆件，可明显弯折调节' },
    { name: '链条悬挂', aliases: ['吊链', '链吊'], remark: '灯体由可见金属链条垂挂' },
    { name: '轨道连接', aliases: ['轨道', '滑轨', '磁吸连接'], remark: '灯头插接/吸附在条形轨道上，可沿轨移动' },
    { name: '鹅颈软管', aliases: ['鹅颈管', '万向软管', '蛇管'], remark: '连接段为可任意弯曲定型的金属软管' },
    { name: '其他', aliases: [], remark: '不属于以上任何连接形态' },
  ],
  D: [
    { name: '吊挂式', aliases: ['吊装', '悬吊', '吊灯'], remark: '整体悬垂于天花板下方，与顶面间有明显空间' },
    { name: '吸顶式', aliases: ['吸顶灯', '贴顶', '半吸顶'], remark: '灯体紧贴天花板安装，无悬垂间隙' },
    { name: '桌面台式', aliases: ['台灯', '桌灯', '床头灯'], remark: '带自重底座放置于桌面，体量小可移动' },
    { name: '落地立式', aliases: ['落地灯', '立式灯', '地灯'], remark: '带落地底座（圆盘/大理石/三脚架），整体立于地面' },
    { name: '壁挂式', aliases: ['壁灯', '挂墙灯'], remark: '灯体固定于墙面，向墙外或上下出光' },
    { name: '嵌入式', aliases: ['暗装', '筒灯', '射灯', '嵌入灯'], remark: '灯体埋入吊顶/墙体，仅露出发光面或边框' },
    { name: '轨道磁吸式', aliases: ['轨道灯', '磁吸轨道灯', '滑轨灯', '无主灯'], remark: '天花上可见条形轨道及轨道上多个灯头模组（磁吸与普通轨道肉眼难分，合并）' },
    { name: '夹持式', aliases: ['夹子灯', '夹灯'], remark: '以弹簧夹/蟹钳夹固定在桌沿或床头' },
    { name: '其他', aliases: ['手提便携灯'], remark: '不属于以上任何安装形态' },
  ],
  F: [
    { name: '无装饰', aliases: ['素面', '极简', '光身'], remark: '灯体表面无任何附加装饰构件' },
    { name: '水晶挂饰', aliases: ['水晶吊坠', '水晶条', '珠帘'], remark: '灯架下垂挂水晶/玻璃坠子（看挂件，区别于 B 水晶罩串）' },
    { name: '金属饰件', aliases: ['黄铜件', '金属包边', '铆钉'], remark: '灯体上有装饰性金属配件/包边/铆钉点缀' },
    { name: '镂空雕花', aliases: ['镂空花纹', '雕花投影', '冲花'], remark: '灯罩/灯体上有镂空花纹，透光形成图案投影' },
    { name: '流苏穗边', aliases: ['流苏', '穗子', '草裙摆'], remark: '罩体下缘垂挂成排流苏/穗条，形似草裙' },
    { name: '彩色玻璃', aliases: ['蒂芙尼', '彩玻', '镶嵌玻璃'], remark: '出光面由多色玻璃拼嵌成图案' },
    { name: '绳编缠绕', aliases: ['麻绳灯', '绳艺', '缠绳'], remark: '灯体/吊杆上有麻绳或织绳缠绕编织装饰' },
    { name: '羽毛装饰', aliases: ['羽毛灯', '羽饰'], remark: '灯体周圈环绕蓬松羽毛层' },
    { name: '木珠串饰', aliases: ['木珠灯', '串珠'], remark: '灯体由木质圆珠成串垂挂构成装饰层' },
    { name: '其他', aliases: ['陶瓷花饰'], remark: '不属于以上任何装饰元素' },
  ],
};

// 品类清单装配（FS/SF 共用 A.1 清单；顺序即种子文件中的组织顺序）
const CATEGORY_LISTS = [
  { code: 'FS', name: '座椅/沙发', list: LIST_FS_SF },
  { code: 'SF', name: '沙发（同 FS 清单）', list: LIST_FS_SF },
  { code: 'TB', name: '茶几', list: LIST_TB },
  { code: 'DT', name: '餐桌', list: LIST_DT },
  { code: 'FC', name: '柜类', list: LIST_FC },
  { code: 'BD', name: '床', list: LIST_BD },
  { code: 'BS', name: '吧椅', list: LIST_BS },
  { code: 'OF', name: '办公家具', list: LIST_OF },
  { code: 'LT', name: '灯具', list: LIST_LT },
];

// ==================== SQL 生成 ====================

function sqlStr(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

function aliasesSql(aliases) {
  if (!aliases || aliases.length === 0) return 'NULL';
  return sqlStr(JSON.stringify(aliases));
}

function buildSeedBlock() {
  const lines = [];
  let total = 0;
  for (const cat of CATEGORY_LISTS) {
    for (const dim of DIM_ORDER) {
      const values = cat.list[dim];
      if (!values || values.length === 0) continue;
      lines.push(`-- 六维 ${dim} 维度 × ${cat.code} ${cat.name}（${values.length} 项）`);
      lines.push('INSERT INTO category_dict (dict_type, dict_code, dict_name, parent_code, sort_order, aliases, remark) VALUES');
      const rows = values.map((v, i) =>
        `(${sqlStr(DIM_TYPES[dim])}, ${sqlStr(cat.code + '-' + v.name)}, ${sqlStr(v.name)}, ${sqlStr(cat.code)}, ${i + 1}, ${aliasesSql(v.aliases)}, ${sqlStr(v.remark)})`
      );
      lines.push(rows.join(',\n'));
      lines.push('ON CONFLICT (dict_type, dict_code) DO NOTHING;');
      lines.push('');
      total += values.length;
    }
  }
  return { block: lines.join('\n').trimEnd() + '\n', total };
}

// V29 静态头部（步骤 0 品类补种 + 步骤 1 存量规范化 + remark 列）
const V29_HEADER = `-- V29：六维标签字典体系（阶段 P0 数据基础）
-- 依据：docs/08-roadmap/六维标签体系完善方案.md 附录 A（v2.1）
-- 本文件由 scripts/generate_six_dim_dict_seed.js 生成，请勿手工编辑枚举种子段。
--
-- 步骤 0（前置）：补种 category 品类字典 DT/BD/LT。
--   AI 品类枚举来自 VisionService.buildCategoryEnumText()（读取 category 字典），
--   不补这三条，AI 永远不会识别出餐桌/床/灯具，三个品类的六维定义永不生效。
-- 步骤 1：dict_code 编码规则 = {品类码}-{中文名}（如 SF-宽厚扶手、TB-直边、DT-直边）。
--   category_dict 主键为 (dict_type, dict_code)，不含 parent_code，
--   多品类同名枚举值（TB/DT 都有"直边"）靠前缀码区分共存；
--   dict_name = 中文名，展示层统一走 resolveDictName 显示名。
--   存量 6 条 FS 六维种子在此规范化为前缀码；与附录 A 清单有对应项的一并改为规范名。
--   （六维字典无 FK 引用、存量 six_dim_tags 实际值为自由文本不引用字典码，改码无下游破坏）
-- 步骤 2：six_dim_A~D/F × 9 品类全量枚举种子（见下方生成段，aliases/remark 随行内联；
--   remark 存视觉判别要点，供 P1 prompt 锚点与识别后归一使用）。
-- 步骤 3：E 维度（表面材质）不建独立枚举，统一引用 material/fabric 字典，本文件不含 six_dim_E 种子。
--
-- 幂等：UPDATE 按旧码定位、INSERT ON CONFLICT DO NOTHING、ALTER IF NOT EXISTS，可重复执行。

-- ==================== 步骤 0：category_dict 增加 remark 列 + 品类字典补种 ====================
ALTER TABLE category_dict ADD COLUMN IF NOT EXISTS remark TEXT;
COMMENT ON COLUMN category_dict.remark IS '备注说明；六维字典存视觉判别要点（一句话锚点），供 AI prompt 注入与识别后归一使用（V29）';

INSERT INTO category_dict (dict_type, dict_code, dict_name, sort_order) VALUES
('category', 'DT', '餐桌', 7),
('category', 'BD', '床', 8),
('category', 'LT', '灯具', 9)
ON CONFLICT (dict_type, dict_code) DO NOTHING;

-- ==================== 步骤 1：存量 FS 六维种子编码规范化 ====================
-- A字架形 → 外露骨架形（附录 A v2.0 修正记录 #7：A字架形并入外露骨架形，A字架形收为其 alias）
UPDATE category_dict SET dict_code = 'FS-外露骨架形', dict_name = '外露骨架形'
WHERE dict_type = 'six_dim_A' AND dict_code = 'A字架形';
-- 蛋形 → 蛋形/球形（附录 A A.1：蛋椅/蛋壳椅/球椅/太空舱椅合并为一项）
UPDATE category_dict SET dict_code = 'FS-蛋形/球形', dict_name = '蛋形/球形'
WHERE dict_type = 'six_dim_A' AND dict_code = '蛋形';
UPDATE category_dict SET dict_code = 'FS-方盒形', dict_name = '方盒形'
WHERE dict_type = 'six_dim_A' AND dict_code = '方盒形';
-- 编织镂空 → 编织镂空靠背（对齐附录 A A.1 B 维度规范名）
UPDATE category_dict SET dict_code = 'FS-编织镂空靠背', dict_name = '编织镂空靠背'
WHERE dict_type = 'six_dim_B' AND dict_code = '编织镂空';
-- 高背包裹：v2.0 已拆分为「高靠背」+「翼形包裹靠背」（两者均在下方种子中），删除遗留枚举避免重复
DELETE FROM category_dict WHERE dict_type = 'six_dim_B' AND dict_code = '高背包裹';
DELETE FROM category_dict WHERE dict_type = 'six_dim_B' AND dict_code = 'FS-高背包裹';
UPDATE category_dict SET dict_code = 'FS-无靠背', dict_name = '无靠背'
WHERE dict_type = 'six_dim_B' AND dict_code = '无靠背';

-- 已规范化存量行补充 aliases/remark（覆盖旧码改名与新装直接插入两种路径，与下方种子内联值一致）
UPDATE category_dict SET aliases = '["A字架形","骨架外露","框架式"]', remark = '木/金属骨架构成整椅主体轮廓（含靠背扶手），软包嵌挂其间'
WHERE dict_type = 'six_dim_A' AND dict_code = 'FS-外露骨架形';
UPDATE category_dict SET aliases = '["蛋椅","蛋壳椅","球椅","太空舱椅"]', remark = '座椅主体呈蛋/球形壳体，人被包裹在壳内'
WHERE dict_type = 'six_dim_A' AND dict_code = 'FS-蛋形/球形';
UPDATE category_dict SET aliases = '["豆腐块","方块沙发","盒子形"]', remark = '外轮廓方正利落、棱角分明、厚度均匀的体块感'
WHERE dict_type = 'six_dim_A' AND dict_code = 'FS-方盒形';
UPDATE category_dict SET aliases = '["藤编靠背","绳编靠背","网面靠背"]', remark = '靠背为编织/网状面，可见透空缝隙'
WHERE dict_type = 'six_dim_B' AND dict_code = 'FS-编织镂空靠背';
UPDATE category_dict SET aliases = '["无背","榻式"]', remark = '坐面之后无任何靠背构件'
WHERE dict_type = 'six_dim_B' AND dict_code = 'FS-无靠背';

-- ==================== 步骤 2：six_dim_A~D/F 全品类枚举种子 ====================
-- E 维度不建独立枚举（步骤 3），统一引用 material/fabric 字典。
`;

function main() {
  const { block, total } = buildSeedBlock();

  // 1. 重写 V29
  fs.writeFileSync(V29_FILE, V29_HEADER + '\n' + block, 'utf8');

  // 2. 替换 V1__seed_data.sql / reset_db.sql 标记区间
  const marked = MARK_BEGIN + '\n' + block + MARK_END;
  const re = new RegExp(
    MARK_BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + MARK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  );
  for (const f of SEED_FILES) {
    const txt = fs.readFileSync(f, 'utf8');
    if (!re.test(txt)) {
      throw new Error(`标记区间未找到：${path.basename(f)}（需先加入 SIX_DIM_DICT_SEED 标记）`);
    }
    fs.writeFileSync(f, txt.replace(re, marked), 'utf8');
  }

  console.log(`已生成六维字典种子 ${total} 条（9 品类 × 5 维度，E 维度不建枚举）`);
  console.log(`  - ${path.relative(ROOT, V29_FILE)}（整体重写）`);
  for (const f of SEED_FILES) console.log(`  - ${path.relative(ROOT, f)}（标记区间替换）`);
}

main();
